### ISSUE TITLE
[Feature request] SphinX relay

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#1758]
https://sphinx.chat/

Manual deployment notes (might be outdated):
https://github.com/stakwork/sphinx-relay/blob/master/docs/raspiblitz_deployment.md

**Comment by rootzoll** [comment]
Lets give it a shot if we can include this into v1.6.2

**Comment by rootzoll** [comment]
OK this is the `app.json` 
```
admin@raspberrypi:/home/sphinxrelay/sphinx-relay $ sudo cat ./config/app.json
{
  "development": {
    "senza_url": "http://localhost:3000/api/v2",
    "macaroon_location": "/Users/evanfeenstra/code/lnd-dev/alice/data/chain/bitcoin/simnet/admin.macaroon",
    "tls_location": "/Users/evanfeenstra/Library/Application Support/Lnd/tls.cert",
    "node_ip": "127.0.0.1",
    "lnd_port": "10001",
    "node_http_protocol": "http",
    "node_http_port": "3002",
    "hub_api_url": "http://lvh.me/api/v1",
    "hub_url": "http://lvh.me/ping",
    "hub_invite_url": "http://lvh.me/invites",
    "hub_check_invite_url": "http://lvh.me/check_invite",
    "media_host": "localhost:5000",
    "tribes_host": "tribes.sphinx.chat"
  },
  "production": {
    "senza_url": "https://staging.senza.us/api/v2/",
    "macaroon_location": "/mnt/hdd/app-data/lnd/data/chain/bitcoin/mainnet/admin.macaroon",
    "tls_location": "/mnt/hdd/app-data/lnd/tls.cert",
    "lnd_log_location": "/mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log",
    "node_ip": "localhost",
    "node_http_protocol": "http",
    "node_http_port": "3300",
    "lnd_port": "10009",
    "hub_api_url": "https://hub.sphinx.chat/api/v1",
    "hub_url": "https://hub.sphinx.chat/ping",
    "hub_invite_url": "https://hub.sphinx.chat/invites",
    "hub_check_invite_url": "https://hub.sphinx.chat/check_invite",
    "media_host": "memes.sphinx.chat",
    "tribes_host": "tribes.sphinx.chat",
    "public_url": "http://192.168.178.95:3300"
  }
}
```

So development has port 3002 and production port 3300 ... but when I start it up it tries to open on port 3001 (which is used on my machine) and fails:
```
admin@raspberrypi:/home/sphinxrelay/sphinx-relay $ sudo -u sphinxrelay env NODE_ENV=production /usr/bin/node dist/app.js
=> env: production
=> [db] starting setup...
=> [db] done syncing
=> [db] setup done
=> [lnd] connecting... attempt #1
(node:12274) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:90:16
    at Generator.next (<anonymous>)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sphinxrelay/sphinx-relay/dist/app.js:4:12)
    at setupApp (/home/sphinxrelay/sphinx-relay/dist/app.js:74:12)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:69:15
    at Generator.next (<anonymous>)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sphinxrelay/sphinx-relay/dist/app.js:4:12)
    at mainSetup (/home/sphinxrelay/sphinx-relay/dist/app.js:64:12)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:47:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/sphinxrelay/sphinx-relay/dist/app.js:5:58)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3001
}
```

**Comment by rootzoll** [comment]
```
admin@raspberrypi:/home/sphinxrelay/sphinx-relay $ sudo cat ./dist/config/app.json
{
  "development": {
    "senza_url": "http://localhost:3000/api/v2",
    "macaroon_location": "/Users/evanfeenstra/code/lnd-dev/alice/data/chain/bitcoin/simnet/admin.macaroon",
    "tls_location": "/Users/evanfeenstra/Library/Application Support/Lnd/tls.cert",
    "node_ip": "127.0.0.1",
    "lnd_port": "10001",
    "node_http_protocol": "http",
    "node_http_port": "3002",
    "hub_api_url": "http://lvh.me/api/v1",
    "hub_url": "http://lvh.me/ping",
    "hub_invite_url": "http://lvh.me/invites",
    "hub_check_invite_url": "http://lvh.me/check_invite",
    "media_host": "localhost:5000",
    "tribes_host": "tribes.sphinx.chat"
  },
  "production": {
    "senza_url": "https://staging.senza.us/api/v2/",
    "macaroon_location": "/mnt/hdd/app-data/lnd/data/chain/bitcoin/mainnet/admin.macaroon",
    "tls_location": "/mnt/hdd/app-data/lnd/tls.cert",
    "lnd_log_location": "/mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log",
    "node_ip": "localhost",
    "node_http_protocol": "http",
    "node_http_port": "3300",
    "lnd_port": "10009",
    "hub_api_url": "https://hub.sphinx.chat/api/v1",
    "hub_url": "https://hub.sphinx.chat/ping",
    "hub_invite_url": "https://hub.sphinx.chat/invites",
    "hub_check_invite_url": "https://hub.sphinx.chat/check_invite",
    "media_host": "memes.sphinx.chat",
    "tribes_host": "tribes.sphinx.chat",
    "public_url": "http://192.168.178.95:3300"
  }
}
```

```
admin@raspberrypi:/home/sphinxrelay/sphinx-relay $ sudo -u sphinxrelay env NODE_ENV=production /usr/bin/node dist/app.js
=> env: production
=> [db] starting setup...
=> [db] done syncing
=> [db] setup done
=> [lnd] connecting... attempt #1
(node:11097) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
(Use `node --trace-deprecation ...` to show where the warning was created)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:90:16
    at Generator.next (<anonymous>)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sphinxrelay/sphinx-relay/dist/app.js:4:12)
    at setupApp (/home/sphinxrelay/sphinx-relay/dist/app.js:74:12)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:69:15
    at Generator.next (<anonymous>)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sphinxrelay/sphinx-relay/dist/app.js:4:12)
    at mainSetup (/home/sphinxrelay/sphinx-relay/dist/app.js:64:12)
    at /home/sphinxrelay/sphinx-relay/dist/app.js:47:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/sphinxrelay/sphinx-relay/dist/app.js:5:58)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3001
}
```

**Comment by rootzoll** [comment]
OK I got the SphinxRelay working in the local network and I prepared now to also have it as an option for IP2TOR.

**Comment by rootzoll** [comment]
Tested recovery/update. Next todos:
- [x] finish IP2Tor option
- [x] add to "MobileApp" with instructions and offering of IP2Tor
- [x] get pairing code and display as QR on LCD
- [x] adapt main menu with hint mobile menu

**Comment by rootzoll** [comment]
- [x] Test IP2TOR with iOS SphinxApp
- [x] Test install on recover (correct app.json)

**Comment by rootzoll** [comment]
OK Sphinx Relay Feature should now be ready to test.

First way:

Go to MAINMENU > UPDATE > PATCH > PATCH-MENU > PATCH & reboot ... you need todo this two times because the patch script itself gets updates the first time. -> then you should find the "Sphinx Relay" option under MAINMENU > SERICES. 

Second way:

Wait for the first release candidate for the v1.6.2 coming up the next days.

**Comment by dennisreimann** [comment]
Awesome – that worked! 👍

Feelin' #reckless again 🚀

**Comment by rootzoll** [comment]
OK did some improvements for IP2TOR setup ... works fine on my machine. Will keep issue open for one last setup test when RC1 is out.

**Comment by rootzoll** [comment]
RaspiBlitz v1.6.2RC1 is out for testing: https://github.com/rootzoll/raspiblitz/issues/1785

**Comment by VitaminB21** [comment]
Installed First way:
`Go to MAINMENU > UPDATE > PATCH > PATCH-MENU > PATCH & reboot ... you need todo this two times because the patch script itself gets updates the first time. -> then you should find the "Sphinx Relay" option under MAINMENU > SERICES.`

I don't get a QR Code to scan? Display and Terminal - nothing to scan ? 

Error on Terminal:  `Failed to encode the input data: Invalid argument`

**Comment by rootzoll** [comment]
@Lace79 can you go to the terminal and run `/home/admin/config.scripts/bonus.sphinxrelay.sh status` .. has the `connectionCode` a value?

**Comment by VitaminB21** [comment]
`connectionCode=''`
it seems it has now value

**Comment by rootzoll** [comment]
Sometime it takes some time. If the connection code has no or outdated value it should give you a warning when you open `SPHINX` in main menu. Did you saw that warning?

**Comment by VitaminB21** [comment]
Yes i saw the warning - it is not locally responding and not over tor. how long does it take?

**Comment by rootzoll** [comment]
From the `status` output test in your browser: http://[localIP]:3300 ... it should answere with `Cannot GET /` then its running locally OK.

**Comment by rootzoll** [comment]
With PR #1796 I made the warning message stronger when Sphinx is not ready yet.

**Comment by openoms** [comment]
https://github.com/stakwork/sphinx-relay/releases
new version v1.1.1
Would it worth it to test and maybe include an update option too?

**Comment by rootzoll** [comment]
Will update the version and quick test. If you like to add an "update option" within th next day that would be great ... I target to package 1.6.2 final (if nothing critical shows up) tomorrow.

**Comment by rootzoll** [comment]
OK updated the version & added an update option. Ready for merge & final testing.

**Comment by openoms** [comment]
got a permission error see PR: https://github.com/rootzoll/raspiblitz/pull/1809

**Comment by openoms** [comment]
also I followed the update method in https://github.com/stakwork/sphinx-relay/blob/master/docs/raspiblitz_deployment.md#fast-method because the THub method would fail to fetch and overwrite the config (since it is in the sphinx-relay dir)

**Comment by rootzoll** [comment]
@openoms ah OK the config overwrite could be a think still on my impelementation. Please rebase again against my latest merge.

**Comment by rootzoll** [comment]
@openoms to preserve the config with the git stash
 does not seem to work - see my test results:
```
./config.scripts/bonus.sphinxrelay.sh update
# making sure services are not running
# Updating Sphinx-Relay
# Stashing the config

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <sphinxrelay@raspberrypi>) not allowed
Cannot save the current index state

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <sphinxrelay@raspberrypi>) not allowed
Cannot save the current index state
# Pulling latest changes...
M	config/app.json
M	config/config.json
Previous HEAD position was b13aec5 Merge pull request #111 from stakwork/fixboost
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
# Reset to the latest release tag
HEAD is now at c545d76 Merge pull request #112 from stakwork/fixboost2
# Reapplying the config
No stash entries found.
# Installing NPM dependencies
npm WARN sequelize-typescript@1.1.0 requires a peer of @types/bluebird@* but none is installed. You must install peer dependencies yourself.
npm WARN sequelize-typescript@1.1.0 requires a peer of @types/validator@* but none is installed. You must install peer dependencies yourself.
npm WARN nodeapp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 880 packages in 102.693s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

# Updated to version v1.1.1

# Starting the sphinxrelay.service ...
admin@raspberrypi:~ $ sudo cat /home/sphinxrelay/sphinx-relay/config/config.json
{
  "development": {
    "dialect": "sqlite",
    "storage": "/Users/Shared/sphinx.db"
  },
  "docker_development": {
    "dialect": "sqlite",
    "storage": "./sphinx.db"
  },
  "test": {
    "dialect": "sqlite",
    "storage": "/home/ubuntu/sphinx.db"
  },
  "production": {
    "dialect": "sqlite",
    "storage": "/relay/.lnd/sphinx.db"
  }
}
```

**Comment by rootzoll** [comment]
Maybe a better and safer solution woulds be also to rewrite the `config.json` on every start with the `write-environment` part of the script ... let me try this out.

**Comment by rootzoll** [comment]
OK this looks good now on my testing :) config gets updated on every start now - so we can just update the code and it will be rewritten on restart.

**Comment by openoms** [comment]
found only one last thing when testing the update: https://github.com/rootzoll/raspiblitz/pull/1812

**Comment by openoms** [comment]
Good to have the update option, the releases are very frequent: https://github.com/stakwork/sphinx-relay/releases/tag/v1.1.3

**Comment by rootzoll** [comment]
Update v1.1.3 tested - will be part of v1.6.2 release. Closing issue.
