### ISSUE TITLE
Offer HTTP for additional apps (as a bridge solution)

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2194]
I started to make additional apps available also thru HTTP while showing the HTTPS with the slef-signed fingerprint next to it. See #2157

Because it was very close to v1.7 relase I was not able to make this consistant for all additional WebApps yet - so here are the ones that need still special care for v1.7.1

**Specter** --> Its in the discussion to remove from WebApp anyway (move to connect as DesktopApp) because HTTPS is a MUST otherwise WebCam access is not possible and we will end up with a self-signed cert waring anyway in v1.8 even when running within Tor browser. See #2193

**Lightning Terminal** --> Is using its own HTTPS server by default. We need to edit it to serve HTTP by default and then integrate it into the NGINX setup with SSL like the other apps. To switch off HTTPS see https://github.com/lightninglabs/lightning-terminal/issues/162 ... we need todo this anyway to allow serving over Tor without any self-signed warnings for v1.8

**BTC-Pay-Server** --> Not sure why yet .. had problems to quickly offer HTTP access to the outside.

**LNbits** --> Throws errors on just http when creating a account (but working on Tor without https):

```
Apr 18 23:42:57 raspberrypi sh[32711]:   URL host invalid, top level domain required (type=value_error.url.host)
Apr 18 23:42:57 raspberrypi sh[32711]: __root__
Apr 18 23:42:57 raspberrypi sh[32711]:   URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'https'})
Apr 18 23:42:57 raspberrypi sh[32711]: During handling of the above exception, another exception occurred:
Apr 18 23:42:57 raspberrypi sh[32711]: Traceback (most recent call last):
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 131, in handle_request
Apr 18 23:42:57 raspberrypi sh[32711]:     return await self.full_dispatch_request(request_context)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 153, in full_dispatch_request
Apr 18 23:42:57 raspberrypi sh[32711]:     result = await self.handle_user_exception(error)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 166, in handle_user_exception
Apr 18 23:42:57 raspberrypi sh[32711]:     return await super().handle_user_exception(error)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1104, in handle_user_exception
Apr 18 23:42:57 raspberrypi sh[32711]:     raise error
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
Apr 18 23:42:57 raspberrypi sh[32711]:     result = await self.dispatch_request(request_context)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1933, in dispatch_request
Apr 18 23:42:57 raspberrypi sh[32711]:     return await handler(**request_.view_args)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 100, in wrapped_view
Apr 18 23:42:57 raspberrypi sh[32711]:     return await view(**kwargs)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/core/views/generic.py", line 106, in wallet
Apr 18 23:42:57 raspberrypi sh[32711]:     "core/wallet.html", user=user, wallet=wallet, service_fee=service_fee
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/templating.py", line 91, in render_template
Apr 18 23:42:57 raspberrypi sh[32711]:     return await _render(template, context)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/templating.py", line 109, in _render
Apr 18 23:42:57 raspberrypi sh[32711]:     rendered_template = await template.render_async(context)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 65, in render_async
Apr 18 23:42:57 raspberrypi sh[32711]:     return self.environment.handle_exception()
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
Apr 18 23:42:57 raspberrypi sh[32711]:     reraise(*rewrite_traceback_stack(source=source))
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
Apr 18 23:42:57 raspberrypi sh[32711]:     raise value.with_traceback(tb)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 25, in concat_async
Apr 18 23:42:57 raspberrypi sh[32711]:     await collect()
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 22, in collect
Apr 18 23:42:57 raspberrypi sh[32711]:     async for event in async_gen:
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/core/templates/core/wallet.html", line 3, in top-level template code
Apr 18 23:42:57 raspberrypi sh[32711]:     {% from "macros.jinja" import window_vars with context %}
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/templates/base.html", line 74, in top-level template code
Apr 18 23:42:57 raspberrypi sh[32711]:     {% endblock %} {% block page_container %}
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/templates/base.html", line 77, in block "page_container"
Apr 18 23:42:57 raspberrypi sh[32711]:     {% block page %}{% endblock %}
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/core/templates/core/wallet.html", line 245, in block "page"
Apr 18 23:42:57 raspberrypi sh[32711]:     <a href="lightning:{{wallet.lnurlwithdraw_full}}">
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
Apr 18 23:42:57 raspberrypi sh[32711]:     return getattr(obj, attribute)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/lnbits/core/models.py", line 55, in lnurlwithdraw_full
Apr 18 23:42:57 raspberrypi sh[32711]:     return lnurl_encode(url)
Apr 18 23:42:57 raspberrypi sh[32711]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/lnurl/core.py", line 26, in encode
Apr 18 23:42:57 raspberrypi sh[32711]:     raise InvalidUrl
Apr 18 23:42:57 raspberrypi sh[32711]: lnurl.exceptions.InvalidUrl
```

**Comment by supertestnet** [comment]
Here is a scenario that just happened:

- User buys a raspiblitz
- User sets up lnbits
- User creates paycode
- User scans paycode
- Wallet gives them error about https://tordomain.onion
- User complains to supertestnet

I asked the lnurl developers about it and they said the lnurl spec doesn't allow https://tordomain.onion and that that is intentional. They indicated that raspiblitzes shouldn't serve lnurls over https. Apparently lnbits can be configured to serve over http, is this something you can fix?

**Comment by supertestnet** [comment]
Here is a scenario that just happened:

- User buys a raspiblitz
- User sets up lnbits
- User creates paycode
- User scans paycode
- Wallet gives them error about https://tordomain.onion
- User complains to supertestnet

I asked the lnurl developers about it and they said the lnurl spec doesn't allow https://tordomain.onion and that that is intentional. They indicated that raspiblitzes shouldn't serve lnurls over https when the user is running over tor. Apparently lnbits can be configured to serve over http, is this something you can fix?

**Comment by rootzoll** [comment]
LNbits needs https to have access as to the Webcam for the Fallback case for LNURL vouchers. I dont have a test setup here at the moment but as far as I remember the LNURLs worked over https as long as its a valid certificate like with LetsEncrypt. And to set this up thats why there are the IP2Tor & LetsEncryt features in RaspiBlitz ... see: https://www.youtube.com/watch?v=0Bt3tHULAnw

If I get you right the problem here is with the Tor-Domain? To have LNURL working over Tor a wallet needs to support Tor ... thats not possible yet with most of the wallets that support LNURL as far as I know. It would be great if someone could research this a bit deeper ... like making a matrix what Lightning-Wallets can already support LNURL over Tor out-of-the-box. Then we could see what special setups are needed to deliver towards that.

**Comment by supertestnet** [comment]
Lnurls don't work when served over an onion address that has an https cert. It violates the lnurl spec to use an https cert with a tor domain. Any wallet that follows the lnurl specification will regard such lnurls as invalid.

The problem is not with the tor domain by itself, it is with a tor domain that has an https cert. I used a wallet that supports tor and lnurls (Simple Bitcoin Wallet) while connected to tor via Orbot (which is the only way Simple Bitcoin Wallet supports tor). I have successfully used this wallet with other lnurls served over tor (served over regular http, no https cert).

When I scanned an lnurl paycode created via raspiblitz, the wallet gave me an error about the https cert because the use of an https cert with a tor domain violates the lnurl specification. I spoke with the lnurl devs in their telegram channel and they said the lack of support for https tor domains is intentional and any service that serves lnurls over https tor domains is acting in violation of the lnurl standard. That's when I added to this issue.

**Comment by frennkie** [comment]
@supertestnet What exactly is the problem? RaspiBlitz hosts LNbits over Tor with HTTP and over Tor with HTTPS. If LNURL requires either HTTPS [x]or TOR+HTTP... then this should work with the default RaspiBlitz setup... or where does this break?
