### ISSUE TITLE
Balance of Satoshis -BOS fails to connect since 1.7

### ISSUE THREAD

**Issue by The34Goon** [raspiblitz/raspiblitz#2289]
**### Balance of Satoshis -BOS fails to connect since 1.7**

bos@username:~ $ bos balance

- 503
- UnexpectedErrorWhenGettingChainBalance
-
  err:
    message: 14 UNAVAILABLE: No connection established
    stack:
      - Error: 14 UNAVAILABLE: No connection established
      -     at Object.callErrorFromStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
      -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
      -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
      -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
      -     at processTicksAndRejections (internal/process/task_queues.js:75:11)
      
Debug:
https://termbin.com/4q34

**Comment by The34Goon** [comment]
removing tlsextradomain= fixed it.
