### ISSUE TITLE
Setup: import grpc fails

### ISSUE THREAD

**Issue by nicolasdiehl** [raspiblitz/raspiblitz#2445]
Formatted 16gb sd card
Formatted 1TB SSD Crucial MX500
Raspberry Pi 4b 4gb
Raspberry Pi 15W USB-C Power Adapter White EU
Inateck USB 3.0 to SATA 2 Cable (connected to usb3 in the center)
Raspiblitz Version: 1.7.0 with .img file

I connected via SSH and ran ./00raspiblitz.sh because the menu was not opening. then I followed the procedure up to creating a ln wallet and setting password c, then: 
> Generating new Wallet ....
> Traceback (most recent call last):
>   File "/home/admin/config.scripts/lnd.initwallet.py", line 7, in <module>
>     import grpc
> ValueError: source code string cannot contain null bytes
> FAIL!! -> MISSING seedwords data - but also no err data ?!?
> CHECK output data above - PRESS ENTER to restart 70initLND.sh

When I'm running python, then import grpc, this happens:

> admin@raspberrypi:~$ python
> Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import grpc
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ValueError: source code string cannot contain null bytes

**Comment by nicolasdiehl** [comment]
```
admin@raspberrypi:~$ uname -a
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
admin@raspberrypi:~$ df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4      6.9G  3.7G  3.0G  56% /
devtmpfs       devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs          tmpfs     1.9G     0  1.9G   0% /dev/shm
tmpfs          tmpfs     1.9G   17M  1.9G   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs          tmpfs      32M     0   32M   0% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   30M  223M  12% /boot
tmpfs          tmpfs     385M     0  385M   0% /run/user/1000
tmpfs          tmpfs     385M     0  385M   0% /run/user/1001
/dev/sda1      ext4      916G   19G  851G   3% /mnt/hdd
```

**Comment by nicolasdiehl** [comment]
The issue was a faulty image file, i extracted again and used balenaEtcher and it worked.
