### ISSUE TITLE
Allow for more than one NODE to be connected to BOS telegram bot

### ISSUE THREAD

**Issue by TrezorHannes** [raspiblitz/raspiblitz#2496]
Tried to connect my second node, while the first one is running quite successful already.
On the second node, I ran 
- bos telegram
- Requested the same API code from BOT-father
- Added API code to the new code
- Triggered /connect in TG prompted the following error in the new node

`? Connection code? (Bot command: /connect) (node:28877) UnhandledPromiseRejectionWarning: Error: 409: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
    at Telegram.callApi (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Polling.[Symbol.asyncIterator] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/polling.js:27:33)
    at async Polling.loop (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/lib/core/network/polling.js:69:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Desirable result would be to have both nodes connected to the same tg BOT and report independently

**Comment by TrezorHannes** [comment]
Arg, wrong Project, Please disregard
