### ISSUE TITLE
C-lightning update to v0.10.2

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2662]
the update to v0.10.2rc1 finishes successfully, but there is a pip error in the beginning:
```
Cloning into 'lightning'...
remote: Enumerating objects: 81588, done.
remote: Counting objects: 100% (3701/3701), done.
remote: Compressing objects: 100% (1618/1618), done.
remote: Total 81588 (delta 2322), reused 3023 (delta 2026), pack-reused 77887
Receiving objects: 100% (81588/81588), 44.92 MiB | 1.90 MiB/s, done.
Resolving deltas: 100% (61689/61689), done.
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-9se81v11/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-9se81v11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-9se81v11/pip-egg-info
         cwd: /tmp/pip-req-build-9se81v11/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-9se81v11/setup.py", line 12, in <module>
        setup(name='pyln-client',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-req-build-9se81v11/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/integration.py", line 65, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-req-build-9se81v11/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 177, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-req-build-9se81v11/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 135, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Submodule 'external/gheap' (https://github.com/valyala/gheap) registered for path 'external/gheap'
```

**Comment by openoms** [comment]
Also should not offer a downgrade as it doesn't work:
![image](https://user-images.githubusercontent.com/43343391/138669184-0a371b28-eded-4cd7-b266-bfa4ccd0d2f5.png)

**Comment by openoms** [comment]
Test success: after updating C-lightning to v0.10.2rc1 the updated version is set up without errors after an SDcard reflash.

**Comment by openoms** [comment]
v0.10.2 is out! https://github.com/ElementsProject/lightning/releases/tag/v0.10.2
![image](https://user-images.githubusercontent.com/43343391/140165556-508ca23f-a834-4be4-b9de-15a74e56d5be.png)
Updating now.

**Comment by openoms** [comment]
Got the same pip error, but otherwise successful both on aarch64 (RPi4) and x86_64 (VM):
```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-be2isc1i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-be2isc1i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-be2isc1i/pip-egg-info
         cwd: /tmp/pip-req-build-be2isc1i/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-be2isc1i/setup.py", line 12, in <module>
        setup(name='pyln-client',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/tmp/pip-req-build-be2isc1i/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/integration.py", line 65, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/tmp/pip-req-build-be2isc1i/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 177, in _get_version
        parsed_version = _do_parse(config)
      File "/tmp/pip-req-build-be2isc1i/.eggs/setuptools_scm-6.3.2-py3.8.egg/setuptools_scm/__init__.py", line 135, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

@rootzoll will we change the version on theSDcard image for v1.7.2? And if so shall we call the cl.install.sh after cloning the raspiblitz repo instead? 
Will include the PGP verification of the git commit / tags there as well then.

**Comment by rootzoll** [comment]
@openoms yeah we will do a new sd card build (and change the version) for v1.7.2 ... if possible we should start reducing code duplication and call now the install-scripts if possible. If changes are done to the sd card build script - please coordinate with @nyxnor to minimize merge conflicts because the https://github.com/rootzoll/raspiblitz/pull/2711#issuecomment-966353446 changes a lot there.

**Comment by openoms** [comment]
ok will:

- [x] refactor the `cl.install.sh` to include git verification as well when installing from source #2686 
- [x] the `build_sdcard.sh` should just call `cl.intall.sh` so will move the relevant steps there

**Comment by rootzoll** [comment]
@openoms during sd card build there was a WARNING on c-lightning install with the mistune lib - do you think thats critical?

```
Collecting mrkd==0.2.0
  Downloading https://www.piwheels.org/simple/mrkd/mrkd-0.2.0-py3-none-any.whl (8.7 kB)
Requirement already satisfied: pygments in /usr/lib/python3/dist-packages (from mrkd==0.2.0) (2.7.1)
Collecting mistune
  Downloading https://www.piwheels.org/simple/mistune/mistune-2.0.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: Jinja2 in /usr/lib/python3/dist-packages (from mrkd==0.2.0) (2.11.3)
Installing collected packages: mistune, mrkd
Successfully installed mistune-2.0.0 mrkd-0.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mistune==0.8.4
  Downloading https://www.piwheels.org/simple/mistune/mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: mistune
  Attempting uninstall: mistune
    Found existing installation: mistune 2.0.0
    Uninstalling mistune-2.0.0:
      Successfully uninstalled mistune-2.0.0
Successfully installed mistune-0.8.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Archive:  clightning-v0.10.2.zip
  inflating: clightning-v0.10.2/.clang-format  
```

**Comment by openoms** [comment]
The downgrading of mistune is intentional: https://github.com/rootzoll/raspiblitz/blob/9652f0542b3f82d37ade6e26320b09e42ce4f819/home.admin/config.scripts/cl.install.sh#L110

the new version was causing issues: https://github.com/ElementsProject/lightning/issues/4973

**Comment by rootzoll** [comment]
@openoms on last test the build sd card script falis to install c-lightning with the following message:

```
install cli/lightning-cli lightningd/lightningd tools/lightning-hsmtool /usr/local/bin
install lightningd/lightning_channeld lightningd/lightning_closingd lightningd/lightning_connectd lightningd/lightning_dualopend lightningd/lightning_gossipd lightningd/lightning_hsmd lightningd/lightning_onchaind lightningd/lightning_openingd lightningd/lightning_websocketd /usr/local/libexec/c-lightning
[ -z "plugins/autoclean plugins/bcli plugins/fetchinvoice plugins/funder plugins/topology plugins/keysend plugins/offers plugins/pay plugins/txprepare plugins/spenderp" ] || install plugins/autoclean plugins/bcli plugins/fetchinvoice plugins/funder plugins/topology plugins/keysend plugins/offers plugins/pay plugins/txprepare plugins/spenderp /usr/local/libexec/c-lightning/plugins
mrkd doc/lightning-cli.1.md
/bin/sh: 1: mrkd: not found
make: *** [doc/Makefile:107: doc/lightning-cli.1] Error 127
```

Any idea?

**Comment by openoms** [comment]
my bad, changed pip to not install to root, but bitcoin instead and the installer ran with admin. Should be fixed with c72b6d2

Update: tested ok

**Comment by rootzoll** [comment]
I am still ending up with an error when building from the latest dev branch ...

```
cp tools/hsmtool tools/lightning-hsmtool
install cli/lightning-cli lightningd/lightningd tools/lightning-hsmtool /usr/local/bin
install lightningd/lightning_channeld lightningd/lightning_closingd lightningd/lightning_connectd lightningd/lightning_dualopend lightningd/lightning_gossipd lightningd/lightning_hsmd lightningd/lightning_onchaind lightningd/lightning_openingd lightningd/lightning_websocketd /usr/local/libexec/c-lightning
[ -z "plugins/autoclean plugins/bcli plugins/fetchinvoice plugins/funder plugins/topology plugins/keysend plugins/offers plugins/pay plugins/txprepare plugins/spenderp" ] || install plugins/autoclean plugins/bcli plugins/fetchinvoice plugins/funder plugins/topology plugins/keysend plugins/offers plugins/pay plugins/txprepare plugins/spenderp /usr/local/libexec/c-lightning/plugins
mrkd doc/lightning-cli.1.md
/bin/sh: 1: mrkd: not found
make: *** [doc/Makefile:107: doc/lightning-cli.1] Error 127
```

**Comment by openoms** [comment]
The problem is even with `sudo` `pip` is not always installing `mrkd` to the same place.
I found that once it is in `/root/.local` (which is not in the path) or the `/usr/local/bin` (which works). 
If fails again we need to make sure that the `PATH` is updated with the location of `mrkd`.

update: removing the `--user` option did it. `mrkd` is now installed to the `/usr/local/bin` reliably

**Comment by rootzoll** [comment]
All tests look good with the RCs .. closing issue for release.
