### ISSUE TITLE
RTL v0.12.1 for LND and CL

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#2860]
first attempt with just modifying the version and install for CL gets to:
```
Jan 02 16:18:57 raspberrypi systemd[1]: Started cRTL Webinterface.
Jan 02 16:18:59 raspberrypi node[1293107]: 
Jan 02 16:18:59 raspberrypi node[1293107]: [02/01/2022, 16:18:59] ERROR: Config => Something went wrong while configuring the node server:
Jan 02 16:18:59 raspberrypi node[1293107]: SyntaxError: Unexpected end of JSON input.
Jan 02 16:18:59 raspberrypi node[1293107]: file:///home/rtl/RTL/backend/utils/config.js:333
Jan 02 16:18:59 raspberrypi node[1293107]:                 throw new Error(err);
Jan 02 16:18:59 raspberrypi node[1293107]:                       ^
Jan 02 16:18:59 raspberrypi node[1293107]: Error: SyntaxError: Unexpected end of JSON input
Jan 02 16:18:59 raspberrypi node[1293107]:     at ConfigService.setServerConfiguration (file:///home/rtl/RTL/backend/utils/config.js:333:23)
Jan 02 16:18:59 raspberrypi node[1293107]:     at ExpressApplication.loadConfiguration (file:///home/rtl/RTL/backend/utils/app.js:32:25)
Jan 02 16:18:59 raspberrypi node[1293107]:     at new ExpressApplication (file:///home/rtl/RTL/backend/utils/app.js:79:14)
Jan 02 16:18:59 raspberrypi node[1293107]:     at file:///home/rtl/RTL/rtl.js:10:13
Jan 02 16:18:59 raspberrypi node[1293107]:     at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
Jan 02 16:18:59 raspberrypi node[1293107]:     at async Loader.import (internal/modules/esm/loader.js:178:24)
Jan 02 16:18:59 raspberrypi node[1293107]:     at async Object.loadESM (internal/process/esm_loader.js:68:5)
Jan 02 16:18:59 raspberrypi systemd[1]: cRTL.service: Main process exited, code=exited, status=1/FAILURE
```
Will likely need the C-lightningREST update: https://github.com/Ride-The-Lightning/c-lightning-REST/releases/tag/v0.6.1

**Comment by rootzoll** [comment]
OK tested install fro CL & LND again. Working. Closing issue for release.
