### ISSUE TITLE
[amd64[ [ZFS] blitzapi error while not getting correct hardware info 

### ISSUE THREAD

**Issue by openoms** [raspiblitz/raspiblitz#3175]
```
₿ sudo journalctl -fu blitzapi
-- Journal begins at Mon 2022-06-20 12:51:05 BST. --
Jun 20 12:59:40 z420 python[12778]: ERROR:asyncio:Task exception was never retrieved
Jun 20 12:59:40 z420 python[12778]: future: <Task finished name='Task-32' coro=<warmup_new_connections() done, defined at ./app/main.py:230> exception=ValueError("invalid literal for int() with base 10: ''")>
Jun 20 12:59:40 z420 python[12778]: Traceback (most recent call last):
Jun 20 12:59:40 z420 python[12778]:   File "./app/main.py", line 304, in warmup_new_connections
Jun 20 12:59:40 z420 python[12778]:     res = await get_hardware_info()
Jun 20 12:59:40 z420 python[12778]:   File "./app/repositories/system.py", line 126, in get_hardware_info
Jun 20 12:59:40 z420 python[12778]:     return await get_hardware_info_impl()
Jun 20 12:59:40 z420 python[12778]:   File "./app/repositories/hardware_impl/raspiblitz.py", line 56, in get_hardware_info_impl
Jun 20 12:59:40 z420 python[12778]:     free = int(await redis_get("hdd_free_bytes"))
Jun 20 12:59:40 z420 python[12778]: ValueError: invalid literal for int() with base 10: ''
Jun 20 14:18:39 z420 python[12778]: INFO:     127.0.0.1:51414 - "POST /system/refresh-token HTTP/1.0" 200 OK
```

![image](https://user-images.githubusercontent.com/43343391/174634810-f8910079-0e46-4d17-8ecd-911111cd029f.png)

```
$ ./_cache.sh get hdd_free_bytes
# _cache.sh get hdd_free_bytes
hdd_free_bytes=""
```
```
₿ sudo config.scripts/blitz.datadrive.sh status
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=2
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.7.2rc1'
isSSD=0
datadisk='hdd'
datapartition='hdd'
hddCandidate='hdd'
hddPartitionCandidate='hdd'
hddBlocksBitcoin=1
hddBytes=1494648619008
hddGigaBytes=1392
config.scripts/blitz.datadrive.sh: line 427: 100 * 1.16 / hddGigaBytes: syntax error: invalid arithmetic operator (error token is ".16 / hddGigaBytes")
error='unkown command'
```

**Comment by openoms** [comment]
ok,  fixed in dev. closing
