### ISSUE TITLE
can't access CLN (or LND) Wallet after failed 1.8rc2 upgrade attempt

### ISSUE THREAD

**Issue by robinvonmises** [raspiblitz/raspiblitz#3203]
I had a running system on 1.7.2, CLN 0.12 and tried to update to 1.8rc2. The upgrade went fine until the system got stock on first fresh reboot and an never ending Lightning Progress: Prepare Sync Loop. Couldn't find a solution, so I tried to switch back to my old 1.7.2 SD Card.

But CLN did not start anymore: "ModuleNotFoundError: No module named 'tqdm'" and some other errors, probably the same as now (see below)

then I created a CL-RESCUE File, upgraded again to 1.8rc2, tried a fresh install, kept the blockchain and recovered from CL-RESCUE

... in the process, the system got stuck on "Preparing Provisioning". Also the "keep blockchain" part was way too quick, seems as it did not erase the SSD.

So, I installed 1.7.2 again and repeated the fresh install, keep blockchain and restore vom CL RESCUE part.

Now I have a running node with CLN and LND not starting:

admin@10.0.0.70:~ ₿ sudo journalctl -u lightningd
-- Journal begins at Fri 2022-01-28 03:21:52 GMT, ends at Fri 2022-07-01 21:55:16 BST. --
Jul 01 17:49:07 raspberrypi systemd[1]: Starting c-lightning daemon on mainnet...
Jul 01 17:49:07 raspberrypi cl.check.sh[829551]: chmod: cannot access '/home/bitcoin/.lightning/bitcoin/lightning-rpc': No s>
Jul 01 17:49:07 raspberrypi systemd[1]: Started c-lightning daemon on mainnet.
Jul 01 17:49:10 raspberrypi sh[829743]: Traceback (most recent call last):
Jul 01 17:49:10 raspberrypi sh[829743]:   File "/home/bitcoin/cl-plugins-enabled/backup.py", line 10, in <module>
Jul 01 17:49:10 raspberrypi sh[829743]:     from backend import Change
Jul 01 17:49:10 raspberrypi sh[829743]:   File "/home/bitcoin/cl-plugins-available/plugins/backup/backend.py", line 7, in <m>
Jul 01 17:49:10 raspberrypi sh[829743]:     from tqdm import tqdm
Jul 01 17:49:10 raspberrypi sh[829743]: ModuleNotFoundError: No module named 'tqdm'
Jul 01 17:49:10 raspberrypi sh[829575]: lightningd: /home/bitcoin/.lightning/config line 39: grpc-port=4772: unrecognized op>
Jul 01 17:49:10 raspberrypi systemd[1]: lightningd.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 17:49:10 raspberrypi systemd[1]: lightningd.service: Failed with result 'exit-code'.
Jul 01 17:49:10 raspberrypi systemd[1]: lightningd.service: Consumed 3.035s CPU time.
Jul 01 17:49:40 raspberrypi systemd[1]: lightningd.service: Scheduled restart job, restart counter is at 1.
Jul 01 17:49:40 raspberrypi systemd[1]: Stopped c-lightning daemon on mainnet.
Jul 01 17:49:40 raspberrypi systemd[1]: lightningd.service: Consumed 3.035s CPU time.
Jul 01 17:49:40 raspberrypi systemd[1]: Starting c-lightning daemon on mainnet...
Jul 01 17:49:40 raspberrypi cl.check.sh[834244]: chmod: cannot access '/home/bitcoin/.lightning/bitcoin/lightning-rpc': No s>
Jul 01 17:49:40 raspberrypi systemd[1]: Started c-lightning daemon on mainnet.
Jul 01 17:49:41 raspberrypi sh[834259]: Traceback (most recent call last):
Jul 01 17:49:41 raspberrypi sh[834259]:   File "/home/bitcoin/cl-plugins-enabled/backup.py", line 10, in <module>
Jul 01 17:49:41 raspberrypi sh[834259]:     from backend import Change
Jul 01 17:49:41 raspberrypi sh[834259]:   File "/home/bitcoin/cl-plugins-available/plugins/backup/backend.py", line 7, in <m>
Jul 01 17:49:41 raspberrypi sh[834259]:     from tqdm import tqdm
Jul 01 17:49:41 raspberrypi sh[834259]: ModuleNotFoundError: No module named 'tqdm'
Jul 01 17:49:41 raspberrypi sh[834246]: lightningd: /home/bitcoin/.lightning/config line 39: grpc-port=4772: unrecognized op>
Jul 01 17:49:41 raspberrypi systemd[1]: lightningd.service: Main process exited, code=exited, status=1/FAILURE
Jul 01 17:49:41 raspberrypi systemd[1]: lightningd.service: Failed with result 'exit-code'.
Jul 01 17:49:41 raspberrypi systemd[1]: lightningd.service: Consumed 2.411s CPU time.
Jul 01 17:50:11 raspberrypi systemd[1]: lightningd.service: Scheduled restart job, restart counter is at 2.
Jul 01 17:50:11 raspberrypi systemd[1]: Stopped c-lightning daemon on mainnet.
Jul 01 17:50:11 raspberrypi systemd[1]: lightningd.service: Consumed 2.411s CPU time.
Jul 01 17:50:11 raspberrypi systemd[1]: Starting c-lightning daemon on mainnet...
Jul 01 17:50:11 raspberrypi cl.check.sh[838100]: chmod: cannot access '/home/bitcoin/.lightning/bitcoin/lightning-rpc': No s>
Jul 01 17:50:11 raspberrypi systemd[1]: Started c-lightning daemon on mainnet.
Jul 01 17:50:12 raspberrypi sh[838115]: Traceback (most recent call last):

Anything I can do? I am thinking of a fresh install without CL-RESCUE first and then again from the already running system, maybe hsm_secret backup only. I know my peers, they could force close, at least that is something

**Comment by robinvonmises** [comment]
the file lightning-rpc does not exist

I tried

patch
config.scripts/cl-plugin.backup.sh off
sudo rm -rf /home/bitcoin/cl-plugins-available/plugins
config.scripts/cl-plugin.backup.sh on

**Comment by robinvonmises** [comment]
Did a fresh Setup on 1.8rc2 now. Fresh LND Node, fresh CLN Node. As everything was set up I did a CL Backup Restore via CL Repair option.

Everything went fine, Node is running now. All channels and funds still there and accessable 😊
