### ISSUE TITLE
LNbits not working after installation

### ISSUE THREAD

**Issue by rene78** [raspiblitz/raspiblitz#3263]
v1.8.0
Hardware: RaspiBlitz with metal case and 4GB RAM

Installed lnbits via the webinterface. Get the following error message when opening the app:
![image](https://user-images.githubusercontent.com/36115705/182002721-426fbb50-4d0d-46d6-a124-fc26ffc2dd86.png)

Here are the logs from lnbits:
```
-- Journal begins at Sat 2022-07-30 15:27:13 BST, ends at Sun 2022-07-31 00:08:02 BST. --
Jul 31 00:07:39 raspberrypi systemd[1]: Started lnbits.
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.08 | INFO | Starting LNbits
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Host: 127.0.0.1
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Port: 5000
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Debug: False
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Site title: LNbits
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Funding source: LndRestWallet
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Database: SQLite
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Data folder: /mnt/hdd/app-data/LNBits
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Git version: 3b98a10c9e65ea35e4e0fc3ff4f417954860f13a
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Started server process [3705305]
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.09 | INFO | Waiting for application startup.
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.19 | ERROR | Traceback (most recent call last):
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
Jul 31 00:07:44 raspberrypi sh[3705305]:     async with self.lifespan_context(app):
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
Jul 31 00:07:44 raspberrypi sh[3705305]:     await self._router.startup()
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
Jul 31 00:07:44 raspberrypi sh[3705305]:     await handler()
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "./lnbits/app.py", line 108, in check_wallet_status
Jul 31 00:07:44 raspberrypi sh[3705305]:     logger.error(
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/loguru/_logger.py", line 1989, in error
Jul 31 00:07:44 raspberrypi sh[3705305]:     __self._log("ERROR", None, False, __self._options, __message, args, kwargs)
Jul 31 00:07:44 raspberrypi sh[3705305]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/loguru/_logger.py", line 1954, in _log
Jul 31 00:07:44 raspberrypi sh[3705305]:     log_record["message"] = message.format(*args, **kwargs)
Jul 31 00:07:44 raspberrypi sh[3705305]: KeyError: '"code"'
Jul 31 00:07:44 raspberrypi sh[3705305]: 2022-07-31 00:07:44.19 | ERROR | Application startup failed. Exiting.
Jul 31 00:07:44 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Jul 31 00:07:44 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Jul 31 00:07:44 raspberrypi systemd[1]: lnbits.service: Consumed 5.115s CPU time.
```

**Comment by rene78** [comment]
Could fix the issue by going to [CONNECT -> RESET.](https://github.com/rootzoll/raspiblitz/issues/3007#issuecomment-1130171980)
Thanks @nicklyk

**Comment by rootzoll** [comment]
Check for v1.8.1 also with new poetry install if its working OK.

**Comment by laurentdebricon** [comment]
i had the same issue, connect -> reset fixed it.
be aware, your blitz will restart.
i had minor errors with connect --> reset
```
# copy macaroons to central app-data directory and ensure unix ownerships and permissions
/bin/cp: cannot stat '/mnt/hdd/lnd/data/chain/bitcoin/mainnet/invoices.macaroon': No such file or directory
/bin/cp: cannot stat '/mnt/hdd/lnd/data/chain/bitcoin/mainnet/chainnotifier.macaroon': No such file or directory
/bin/cp: cannot stat '/mnt/hdd/lnd/data/chain/bitcoin/mainnet/signer.macaroon': No such file or directory
/bin/cp: cannot stat '/mnt/hdd/lnd/data/chain/bitcoin/mainnet/walletkit.macaroon': No such file or directory
/bin/cp: cannot stat '/mnt/hdd/lnd/data/chain/bitcoin/mainnet/router.macaroon': No such file or directory
```
