### ISSUE TITLE
BTCPayserver not starting up successfully after cert renewal via ~/.acme.sh/acme.sh

### ISSUE THREAD

**Issue by TrezorHannes** [raspiblitz/raspiblitz#3323]
Logging on behalf of a fellow node-runner.

### Problem Description
The BTCPayserver & LNBits domain.duckdns.org certificate caused issues with Chrome and Firefox, so we called 
```
export DuckDNS_Token="abcdefgh-0123-56ij-78kl-abcd9012efgh"
~/.acme.sh/acme.sh --issue --keylength ec-256 --dns dns_duckdns -d hostname.duckdns.org -d *.hostname.duckdns.org
```
with the above placeholders adjusted. This resolved the certification issues in the browser. 

But the next day, we've identified that BTCPayserver isn't starting up properly anymore, which is a pressing issue since customers are actively using it.

Narrowed down the issue, `cat /var/log/nginx/error_btcpay.log`
```
2022/09/19 19:25:10 [error] 1372010#1372010: *290 connect() failed (111: Connection refused) while connecting to upstream, client: [37.201.194.175](http://XXX.XXX.XXX.XXX/), server: _, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:23000/", host: "[freenode.duckdns.org:23001](http://freenode.duckdns.org:23001/)"
```
The port 23000 not listening `sudo netstat -tulpen | grep 23000` indicating that BTCPayserver isn't running. So we looked into the journal with `sudo journalctl -xeu btcpayserver.service`, and identified the following errors

#### Normal startup section
```
░░ The job identifier is 3205.
Sep 19 21:42:51 raspberrypi dotnet[95374]: info: Configuration:  Data Directory: /home/btcpay/.btcpayserver/Main
Sep 19 21:42:51 raspberrypi dotnet[95374]: info: Configuration:  Configuration File: /home/btcpay/.btcpayserver/Main/settings.config
Sep 19 21:42:53 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Loading plugins from /home/btcpay/.btcpayserver/Plugins
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.6.9.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.6.9.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.6.9.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Custodians.Fake - 1.0.0.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.LNbank - 1.2.3.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.0.4.0
Sep 19 21:42:57 raspberrypi dotnet[95374]: info: Configuration:  Supported chains: BTC
Sep 19 21:42:58 raspberrypi dotnet[95374]: info: Configuration:  BTC: Explorer url is http://127.0.0.1:24444/
Sep 19 21:42:58 raspberrypi dotnet[95374]: info: Configuration:  BTC: Cookie file is /home/btcpay/.nbxplorer/Main/.cookie
Sep 19 21:42:58 raspberrypi dotnet[95374]: info: Configuration:  Network: Mainnet
Sep 19 21:43:07 raspberrypi dotnet[95374]: info: Configuration:  Root Path: /
```
... continued below

#### Error section
```
Sep 19 21:43:10 raspberrypi dotnet[95374]: Application startup exception: System.InvalidOperationException: No backing field could be found for property 'Transaction.Date' and the property does not have a setter.
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateFieldMapping(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.LNbank.LNbankPlugin.Execute(IApplicationBuilder applicationBuilder, IServiceProvider applicationBuilderApplicationServices) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/LNbankPlugin.cs:line 46
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.PluginManager.UsePlugins(IApplicationBuilder applicationBuilder) in /home/btcpay/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 161
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.ConfigureCore(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, IOptions`1 dataDirectories, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 297
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, BTCPayServerOptions options, IOptions`1 dataDirectories, ILoggerFactory loggerFactory, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 218
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Sep 19 21:43:10 raspberrypi dotnet[95374]: crit: Microsoft.AspNetCore.Hosting.Diagnostics: Application startup exception
Sep 19 21:43:10 raspberrypi dotnet[95374]: System.InvalidOperationException: No backing field could be found for property 'Transaction.Date' and the property does not have a setter.
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateFieldMapping(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.LNbank.LNbankPlugin.Execute(IApplicationBuilder applicationBuilder, IServiceProvider applicationBuilderApplicationServices) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/LNbankPlugin.cs:line 46
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.PluginManager.UsePlugins(IApplicationBuilder applicationBuilder) in /home/btcpay/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 161
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.ConfigureCore(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, IOptions`1 dataDirectories, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 297
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, BTCPayServerOptions options, IOptions`1 dataDirectories, ILoggerFactory loggerFactory, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 218
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Sep 19 21:43:10 raspberrypi dotnet[95374]: Unhandled exception. System.InvalidOperationException: No backing field could be found for property 'Transaction.Date' and the property does not have a setter.
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateFieldMapping(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.LNbank.LNbankPlugin.Execute(IApplicationBuilder applicationBuilder, IServiceProvider applicationBuilderApplicationServices) in /home/d11n/Sources/btcpay/server/BTCPayServer.Plugins.LNbank/LNbankPlugin.cs:line 46
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Plugins.PluginManager.UsePlugins(IApplicationBuilder applicationBuilder) in /home/btcpay/btcpayserver/BTCPayServer/Plugins/PluginManager.cs:line 161
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.ConfigureCore(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, IOptions`1 dataDirectories, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 297
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Hosting.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider prov, BTCPayServerOptions options, IOptions`1 dataDirectories, ILoggerFactory loggerFactory, IRateLimitService rateLimits) in /home/btcpay/btcpayserver/BTCPayServer/Hosting/Startup.cs:line 218
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.StartWithTasksAsync(IWebHost webHost, CancellationToken cancellationToken) in /home/btcpay/btcpayserver/BTCPayServer/Extensions/WebHostExtensions.cs:line 23
Sep 19 21:43:10 raspberrypi dotnet[95374]:    at BTCPayServer.Program.Main(String[] args) in /home/btcpay/btcpayserver/BTCPayServer/Program.cs:line 70
Sep 19 21:43:10 raspberrypi systemd[1]: btcpayserver.service: Main process exited, code=exited, status=134/n/a
```

### Next steps
We've got no idea and appreciate any suggestions on how to move forward. 
- Dotnet issues, should we look into reinstalling this?
- since it appeared right after an .acme update, is it related to the pulled certs? Does `/home/btcpay/.btcpayserver/Main/settings.config` need an update in the `certthumbprint` fingerprint?
- Can BTCPayserver be uninstalled and reinstalled without losing all customer data configuration?
- What else might be the reason for the wall of errors? Could it be related to a gRPC issue [mentioned here](https://github.com/dotnet/efcore/issues/23703#issuecomment-752474168)?

Thanks so much for any hint what might help us.

**Comment by TrezorHannes** [comment]
Solved by reinstalling. We had to discard the previous customer data, but pg_dump'ed it so perhaps this is sufficient to reload it.
