### ISSUE TITLE
Lighting sync stuck at 99.99%

### ISSUE THREAD

**Issue by Haightz** [raspiblitz/raspiblitz#3367]
Hello
Blockchain is 100% but lighting sync has been stuck at 99.99% for a few days now. I have restarted the node twice and still the same issue. This is not an initial setup. 

***************************************************************
* RASPIBLITZ DEBUG LOGS
***************************************************************
blitzversion: 1.7.0
chainnetwork: bitcoin / main
 08:25:17 up 1 day,  1:35,  2 users,  load average: 0.46, 0.62, 0.67

*** BLOCKCHAIN SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-10-13 06:51:38 BST; 1 day 1h ago
 Main PID: 2645 (bitcoind)
    Tasks: 18 (limit: 4915)
   CGroup: /system.slice/bitcoind.service
           └─2645 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin/bitcoin.conf -pid=/mnt/hdd/bitcoin/bitco…

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

*** LAST BLOCKCHAIN ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n8
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
-- No entries --

*** LAST BLOCKCHAIN 20 INFO LOGS ***
sudo tail -n 20 /mnt/hdd/bitcoin/debug.log
2022-10-14T06:37:40Z UpdateTip: new best=000000000000000000012b13afb76d3003a6481642ec626f5e2a64ffc92a4170 height=758591 version=0x20002004 log2_work=93.784031 tx=772068771 date='2022-10-14T06:37:27Z' progress=1.000000 cache=20.4MiB(52484txo)
2022-10-14T06:39:31Z UpdateTip: new best=000000000000000000043fd12675c71c29cf0bfbaa837e01cc1b91bba2a6b91e height=758592 version=0x2c264000 log2_work=93.784044 tx=772069084 date='2022-10-14T06:39:08Z' progress=1.000000 cache=20.6MiB(54129txo)
2022-10-14T06:42:23Z UpdateTip: new best=00000000000000000002b7bc0448b657dcec35a312b077f751798b7c118707f4 height=758593 version=0x20200000 log2_work=93.784057 tx=772069550 date='2022-10-14T06:41:51Z' progress=1.000000 cache=20.9MiB(55802txo)
2022-10-14T06:42:23Z BlockUntilSyncedToCurrentChain: txindex is catching up on block notifications
2022-10-14T06:48:26Z Socks5() connect to s7m4mnd6bokujhywsocxibispktruormushdroeaeqeb3imvztfs3vid.onion:8333 failed: host unreachable
2022-10-14T06:50:45Z Socks5() connect to xlpi353v7ia5b73msynr7tmddgxoco7n2r2bljt5txpv6bpzzphkreyd.onion:8333 failed: host unreachable
2022-10-14T06:51:37Z Socks5() connect to ldvhlpsrvspquqnl3gutz7grfu5lb3m2dgnezpl3tlkxgpoiw2g5mzid.onion:8333 failed: host unreachable
2022-10-14T06:51:47Z socket send error Broken pipe (32)
2022-10-14T06:57:42Z Socks5() connect to ldvhlpsrvspquqnl3gutz7grfu5lb3m2dgnezpl3tlkxgpoiw2g5mzid.onion:8333 failed: host unreachable
2022-10-14T07:00:44Z UpdateTip: new best=00000000000000000000ffb61ef2049ecdb68f709da4e7d1e44852748d69f2dd height=758594 version=0x2000e000 log2_work=93.784070 tx=772072308 date='2022-10-14T07:00:17Z' progress=1.000000 cache=22.4MiB(68679txo)
2022-10-14T07:01:52Z socket send error Broken pipe (32)
2022-10-14T07:02:31Z Socks5() connect to xlpi353v7ia5b73msynr7tmddgxoco7n2r2bljt5txpv6bpzzphkreyd.onion:8333 failed: host unreachable
2022-10-14T07:03:10Z Socks5() connect to s7m4mnd6bokujhywsocxibispktruormushdroeaeqeb3imvztfs3vid.onion:8333 failed: host unreachable
2022-10-14T07:07:59Z socket send error Broken pipe (32)
2022-10-14T07:10:53Z socket send error Broken pipe (32)
2022-10-14T07:10:58Z Socks5() connect to xlpi353v7ia5b73msynr7tmddgxoco7n2r2bljt5txpv6bpzzphkreyd.onion:8333 failed: host unreachable
2022-10-14T07:11:35Z Socks5() connect to s7m4mnd6bokujhywsocxibispktruormushdroeaeqeb3imvztfs3vid.onion:8333 failed: host unreachable
2022-10-14T07:11:53Z UpdateTip: new best=00000000000000000002eef367f1512cec84bc2dea6a6fd249988c95cdf28dd6 height=758595 version=0x37ffe004 log2_work=93.784083 tx=772073968 date='2022-10-14T07:11:28Z' progress=1.000000 cache=24.9MiB(89019txo)
2022-10-14T07:12:05Z Socks5() connect to gliovxxzyy2rkwaoz25khf6oa64c3csqzjn3t6dodsjuf34w6a6ktsyd.onion:8333 failed: host unreachable
2022-10-14T07:20:46Z Socks5() connect to gliovxxzyy2rkwaoz25khf6oa64c3csqzjn3t6dodsjuf34w6a6ktsyd.onion:8333 failed: host unreachable

*** LND SYSTEMD STATUS ***
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-10-13 06:51:38 BST; 1 day 1h ago
 Main PID: 2650 (lnd)
    Tasks: 10 (limit: 4915)
   CGroup: /system.slice/lnd.service
           └─2650 /usr/local/bin/lnd --tor.active --tor.streamisolation --tor.v3 --tor.socks=9070 --tor.control=9071 --…

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

*** LAST LND ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
-- No entries --

*** LAST 30 LND INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2022-10-14 07:42:23.724 [DBG] LNWL: Received block connected notification for height 758593 while rescanning
2022-10-14 08:00:44.595 [DBG] LNWL: Filtering block 758594 (00000000000000000000ffb61ef2049ecdb68f709da4e7d1e44852748d69f2dd) with 2758 transactions
2022-10-14 08:00:45.162 [DBG] LNWL: Received block connected notification for height 758594 while rescanning
2022-10-14 08:01:35.791 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:02:22.088 [ERR] RPCS: [/lnrpc.Lightning/ConnectPeer]: server is still in the process of starting
2022-10-14 08:08:52.164 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.264 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.406 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.547 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.695 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.838 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:08:59.982 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:09:00.124 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:09:07.564 [DBG] RPCS: [feereport]
2022-10-14 08:09:07.735 [DBG] RPCS: [feereport]
2022-10-14 08:09:07.884 [DBG] RPCS: [feereport]
2022-10-14 08:09:08.034 [DBG] RPCS: [feereport]
2022-10-14 08:09:08.189 [DBG] RPCS: [feereport]
2022-10-14 08:09:25.912 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:11:53.705 [DBG] LNWL: Filtering block 758595 (00000000000000000002eef367f1512cec84bc2dea6a6fd249988c95cdf28dd6) with 1660 transactions
2022-10-14 08:11:54.146 [DBG] LNWL: Received block connected notification for height 758595 while rescanning
2022-10-14 08:13:15.893 [DBG] RPCS: [listpeers] yielded [] peers
2022-10-14 08:13:15.957 [DBG] RPCS: [pendingchannels]
2022-10-14 08:13:15.957 [DBG] RPCS: [listchannels] fetched 1 channels from DB
2022-10-14 08:13:15.953 [DBG] RPCS: [channelbalance] local_balance=177098846 mSAT remote_balance=271880154 mSAT unsettled_local_balance=0 mSAT unsettled_remote_balance=0 mSAT pending_open_local_balance=0 mSAT pending_open_remote_balance=0 mSAT
2022-10-14 08:13:16.155 [DBG] RPCS: [ListPayments]
2022-10-14 08:13:16.190 [DBG] RPCS: [feereport]
2022-10-14 08:13:16.219 [DBG] RPCS: [walletbalance] Total balance=0.00049846 BTC (confirmed=0.00049846 BTC, unconfirmed=0 BTC)
2022-10-14 08:13:16.270 [DBG] RPCS: [forwardinghistory]
2022-10-14 08:13:55.653 [ERR] RPCS: [/lnrpc.Lightning/ConnectPeer]: server is still in the process of starting

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/nginx.service.d
           └─raspiblitz.conf
   Active: failed (Result: exit-code) since Thu 2022-10-13 06:50:49 BST; 1 day 1h ago
     Docs: man:nginx(8)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
-- No entries --
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

*** LAST 20 TOUCHSCREEN LOGS ***
sudo tail -n 20 /home/pi/.cache/lxsession/LXDE-pi/run.log
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
** Message: 01:44:02.973: wlan0: Received scan results
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
** Message: 01:45:03.021: wlan0: Received scan results
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
** Message: 01:46:02.982: wlan0: Received scan results
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
** Message: 01:47:02.989: wlan0: Received scan results
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
Playing WAVE '/usr/share/piwiz/srprompt.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono

*** LAST 20 LOOP LOGS ***
sudo journalctl -u loopd -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
-- No entries --

*** LAST 20 RTL LOGS ***
sudo journalctl -u RTL -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
Oct 14 08:13:55 raspberrypi node[2652]: [1B blob data]
Oct 14 08:13:55 raspberrypi node[2652]: ERROR: Peers(63) => Add Peer Error: "server is still in the process of starting"
Oct 14 08:13:55 raspberrypi node[2652]: Unhandled rejection StatusCodeError: 500 - {"error":"server is still in the process of starting","code":2,"message":"server is still in the process of starting","details":[]}
Oct 14 08:13:55 raspberrypi node[2652]:     at new StatusCodeError (/home/rtl/RTL/node_modules/request-promise-core/lib/errors.js:32:15)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.plumbing.callback (/home/rtl/RTL/node_modules/request-promise-core/lib/plumbing.js:104:33)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.RP$callback [as _callback] (/home/rtl/RTL/node_modules/request-promise-core/lib/plumbing.js:46:31)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.self.callback (/home/rtl/RTL/node_modules/request/request.js:185:22)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.emit (events.js:315:20)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.<anonymous> (/home/rtl/RTL/node_modules/request/request.js:1154:10)
Oct 14 08:13:55 raspberrypi node[2652]:     at Request.emit (events.js:315:20)
Oct 14 08:13:55 raspberrypi node[2652]:     at IncomingMessage.<anonymous> (/home/rtl/RTL/node_modules/request/request.js:1076:12)
Oct 14 08:13:55 raspberrypi node[2652]:     at Object.onceWrapper (events.js:421:28)
Oct 14 08:13:55 raspberrypi node[2652]:     at IncomingMessage.emit (events.js:327:22)
Oct 14 08:13:55 raspberrypi node[2652]:     at endReadableNT (internal/streams/readable.js:1327:12)
Oct 14 08:13:55 raspberrypi node[2652]:     at processTicksAndRejections (internal/process/task_queues.js:80:21)

*** LAST 20 ElectRS LOGS ***
sudo journalctl -u electrs -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:17 BST. --
Oct 14 08:18:35 raspberrypi electrs[2651]: 2022-10-14T08:18:35.896+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:18:56 raspberrypi electrs[2651]: 2022-10-14T08:18:56.047+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:19:16 raspberrypi electrs[2651]: 2022-10-14T08:19:16.161+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:19:36 raspberrypi electrs[2651]: 2022-10-14T08:19:36.314+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:19:56 raspberrypi electrs[2651]: 2022-10-14T08:19:56.391+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:20:16 raspberrypi electrs[2651]: 2022-10-14T08:20:16.613+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:20:36 raspberrypi electrs[2651]: 2022-10-14T08:20:36.944+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:20:57 raspberrypi electrs[2651]: 2022-10-14T08:20:57.205+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:21:17 raspberrypi electrs[2651]: 2022-10-14T08:21:17.432+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:21:37 raspberrypi electrs[2651]: 2022-10-14T08:21:37.691+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:21:57 raspberrypi electrs[2651]: 2022-10-14T08:21:57.786+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:22:18 raspberrypi electrs[2651]: 2022-10-14T08:22:18.134+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:22:38 raspberrypi electrs[2651]: 2022-10-14T08:22:38.374+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:22:58 raspberrypi electrs[2651]: 2022-10-14T08:22:58.703+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:23:19 raspberrypi electrs[2651]: 2022-10-14T08:23:19.032+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:23:39 raspberrypi electrs[2651]: 2022-10-14T08:23:39.302+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:23:59 raspberrypi electrs[2651]: 2022-10-14T08:23:59.418+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:24:19 raspberrypi electrs[2651]: 2022-10-14T08:24:19.769+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:24:39 raspberrypi electrs[2651]: 2022-10-14T08:24:39.951+01:00 - TRACE - RPC PeriodicUpdate
Oct 14 08:25:00 raspberrypi electrs[2651]: 2022-10-14T08:25:00.421+01:00 - TRACE - RPC PeriodicUpdate

*** ElectRS Status ***
##### STATUS ELECTRS SERVICE
configured=1
serviceInstalled=1
serviceRunning=1
tipSynced=1
electrumResponding=1
initialSynced=1
localIP='192.168.1.77'
portTCP='50001'
localTCPPortActive=1
publicTCPPortAnswering=0
portHTTP='50002'
localHTTPPortActive=0
publicHTTPPortAnswering=0
TORrunning=1
nginxTest=1

*** LAST 20 LIT LOGS ***
sudo journalctl -u litd -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** LAST 20 BTCPayServer LOGS ***
sudo journalctl -u btcpayserver -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** LAST 20 LNbits LOGS ***
sudo journalctl -u lnbits -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** LAST 20 Thunderhub LOGS ***
sudo journalctl -u thunderhub -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** LAST 20 SPECTER LOGS ***
sudo journalctl -u cryptoadvance-specter -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** LAST 20 SPHINX LOGS ***
sudo journalctl -u sphinxrelay -b --no-pager -n20
-- Logs begin at Thu 2022-10-13 13:03:34 BST, end at Fri 2022-10-14 08:25:22 BST. --
-- No entries --

*** MOUNTED DRIVES ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       59G  8.0G   49G  15% /
devtmpfs       devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     3.9G  4.0K  3.9G   1% /dev/shm
tmpfs          tmpfs     3.9G  393M  3.5G  10% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs          tmpfs      32M     0   32M   0% /var/cache/raspiblitz
/dev/mmcblk0p1 vfat      253M   30M  223M  12% /boot
/dev/sda1      ext4      916G  635G  236G  73% /mnt/hdd
tmpfs          tmpfs     787M     0  787M   0% /run/user/1000
tmpfs          tmpfs     787M     0  787M   0% /run/user/1001

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
isSSD=0
datadisk='sda'
datapartition='sda1'
hddBlocksBitcoin=1
hddBlocksLitecoin=0
hddBytes=1000203091968
hddGigaBytes=931
hddUsedInfo='635G (73%)'
hddDataFreeKB=246687740
hddAdapterUSB='174c:1153'
hddAdapterUSAP=0

# RAID
isRaid=0
raidCandidates=0

# SWAP
isSwapExternal=1
SwapExternalPath='/mnt/hdd/swapfile'

*** NETWORK ***
localip=192.168.1.77
dhcp=1
network_device=eth0

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM STATUS (can take some seconds to gather) ***
localIP='192.168.1.77'
tempCelsius='51.1'
uptime=92108
upsStatus='OFF'
startcountBlockchain=1
bitcoinActive=1
blockchainHeight=758595
initialSync=0
syncProgress=100.00
startcountLightning=1
lndActive=1
walletLocked=0
lndPeers=0
syncedToChain=0
scanTimestamp=1665731488
scanDate='Fri 14 Oct 08:11:28 BST 2022'
scanProgress=99.99
lndRPCReady=1
blitzTUIActive=0
blitzTUIRestarts=0
scriptRuntime=0

*** OPTION: SHARE THIS DEBUG OUTPUT ***
An easy way to share this debug output on GitHub or on a support chat
use the following command and share the resulting link:
/home/admin/XXdebugLogs.sh | nc termbin.com 9999

**Comment by BCsRock** [comment]
It's a recent bug in LND implementation which cannot process one particular taproot transaction. Just update the Image to version 1.0.8b and it will work. 
See https://github.com/rootzoll/raspiblitz/commit/ace3e21a9c18bee8a5cce7d43c286036c9a847c7

**Comment by Haightz** [comment]
> It's a recent bug in LND implementation which cannot process one particular taproot transaction. Just update the Image to version 1.0.8b and it will work. See [ace3e21](https://github.com/rootzoll/raspiblitz/commit/ace3e21a9c18bee8a5cce7d43c286036c9a847c7)

Thank you back up running!
