### ISSUE TITLE
LND failing to start

### ISSUE THREAD

**Issue by willrunge** [raspiblitz/raspiblitz#3491]
My node has been stuck on 'prepare sync' for quite some time now and it seems to be stuck in loop with some bad input on startup. I see an index issue `panic: runtime error: index out of range [7] with length 0`. Is there any other log I can check to give me more insight? Any ideas what I might need to do? Manually stopping and starting the service again fails as well.

```
Dec 02 18:04:38 raspberrypi systemd[1]: lnd.service: Scheduled restart job, restart counter is at 852.
Dec 02 18:04:38 raspberrypi systemd[1]: Stopped Lightning Network Daemon.
Dec 02 18:04:38 raspberrypi systemd[1]: Starting Lightning Network Daemon...
Dec 02 18:04:39 raspberrypi lnd[1474947]: panic: runtime error: index out of range [7] with length 0
Dec 02 18:04:39 raspberrypi lnd[1474947]: goroutine 1 [running]:
Dec 02 18:04:39 raspberrypi lnd[1474947]: encoding/binary.bigEndian.Uint64(...)
Dec 02 18:04:39 raspberrypi lnd[1474947]:         encoding/binary/binary.go:125
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd/kvdb.lastCompactionDate({0x4000510600?, 0x300000002?})
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/kvdb@v1.3.1/backend.go:226 +0x194
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd/kvdb.compactAndSwap(0x4000717170)
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/kvdb@v1.3.1/backend.go:127 +0xd4
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd/kvdb.GetBoltBackend(0x4000717170)
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/kvdb@v1.3.1/backend.go:101 +0x78
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd/lncfg.(*DB).GetBackends(0x4000530900, {0x1a022b8?, 0x40003e8180}, {0x40000c88a0, 0x25}, {0x4000538540, 0x2d}, {0x4000125e80, 0x32}, 0x1, ...)
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/lncfg/db.go:458 +0x2318
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd.(*DefaultDatabaseBuilder).BuildDatabase(0x400000d7a0, {0x1a022b8, 0x40003e8180})
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/config_builder.go:809 +0x280
Dec 02 18:04:39 raspberrypi lnd[1474947]: github.com/lightningnetwork/lnd.Main(0x400059ab00, {{0x0?, 0x400007e5a0?, 0x400007e600?}}, 0x40000b2780, {0x4000348480, 0x400007e5a0, 0x400007e600, 0x400007e660, {0x0}})
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/lnd.go:355 +0x1454
Dec 02 18:04:39 raspberrypi lnd[1474947]: main.main()
Dec 02 18:04:39 raspberrypi lnd[1474947]:         github.com/lightningnetwork/lnd/cmd/lnd/main.go:38 +0x1ac
Dec 02 18:04:39 raspberrypi systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 02 18:04:39 raspberrypi systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 02 18:04:39 raspberrypi systemd[1]: Failed to start Lightning Network Daemon.
```

**Comment by openoms** [comment]
Looks like your LND database is corrupt. MAke sure to have the seed and the latest channel.backup and proceed to recover from SEED + SCB.
