### ISSUE TITLE
Use Core Lightning JSON RPC interface by default

### ISSUE THREAD

**Issue by fusion44** [raspiblitz/raspiblitz#3733]
The API now supports the UNIX socket JSON RPC interface of Core Lightning. This should be the preferred way of connecting to Core Lightning for now. To activate, the `.env` file must contain the following settings:

```.env
ln_node=cln_jrpc

# cln json rpc - path to the socket file
cln_jrpc_path="/mnt/hdd/app-data/.lightning/bitcoin/lightning-rpc"
```
Note that `cln_jrpc_path` variable in the `.env_sample` file already points to the correct path on the RaspiBlitz.

**Comment by rootzoll** [comment]
@fusion44  `ln_node=lnd_jrpc` should be `ln_node=cln_jrpc, correct?

**Comment by fusion44** [comment]
@rootzoll Oh dang, yes correct. I've edited the original post!

**Comment by rootzoll** [comment]
@fusion44 When running the JRPC I get the following error when trying to use the WebUI on the API: 

FYI - this is a fresh setup node with no transaction history so far

```
Apr 08 17:29:17 raspberrypi python[742]: 2023-04-08 17:29:17 | ❌ | cln_jrpc.py:197 | get_ln_info() returned None
Apr 08 17:29:17 raspberrypi python[742]: 2023-04-08 17:29:17 | ❌ | service.py:84 | An error has been caught in function 'list_all_tx', process 'MainProcess' (742), thread 'MainThread' (548168671296):
Apr 08 17:29:17 raspberrypi python[742]: Traceback (most recent call last):
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Apr 08 17:29:17 raspberrypi python[742]:     return _run_code(code, main_globals, None,
Apr 08 17:29:17 raspberrypi python[742]:            │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'uvicorn', '__loader__': <_frozen_importlib_external.SourceFileLoade...
Apr 08 17:29:17 raspberrypi python[742]:            │         └ <code object <module> at 0x7fa0d93450, file "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/__main__.py", ...
Apr 08 17:29:17 raspberrypi python[742]:            └ <function _run_code at 0x7fa0d8fc10>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
Apr 08 17:29:17 raspberrypi python[742]:     exec(code, run_globals)
Apr 08 17:29:17 raspberrypi python[742]:          │     └ {'__name__': '__main__', '__doc__': None, '__package__': 'uvicorn', '__loader__': <_frozen_importlib_external.SourceFileLoade...
Apr 08 17:29:17 raspberrypi python[742]:          └ <code object <module> at 0x7fa0d93450, file "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/__main__.py", ...
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/__main__.py", line 4, in <module>
Apr 08 17:29:17 raspberrypi python[742]:     uvicorn.main()
Apr 08 17:29:17 raspberrypi python[742]:     │       └ <Command main>
Apr 08 17:29:17 raspberrypi python[742]:     └ <module 'uvicorn' from '/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/__init__.py'>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     return self.main(*args, **kwargs)
Apr 08 17:29:17 raspberrypi python[742]:            │    │     │       └ {}
Apr 08 17:29:17 raspberrypi python[742]:            │    │     └ ()
Apr 08 17:29:17 raspberrypi python[742]:            │    └ <function BaseCommand.main at 0x7fa05403a0>
Apr 08 17:29:17 raspberrypi python[742]:            └ <Command main>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
Apr 08 17:29:17 raspberrypi python[742]:     rv = self.invoke(ctx)
Apr 08 17:29:17 raspberrypi python[742]:          │    │      └ <click.core.Context object at 0x7fa0e39040>
Apr 08 17:29:17 raspberrypi python[742]:          │    └ <function Command.invoke at 0x7fa053e8b0>
Apr 08 17:29:17 raspberrypi python[742]:          └ <Command main>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
Apr 08 17:29:17 raspberrypi python[742]:     return ctx.invoke(self.callback, **ctx.params)
Apr 08 17:29:17 raspberrypi python[742]:            │   │      │    │           │   └ {'port': 11111, 'host': '0.0.0.0', 'root_path': '/api', 'app': 'app.main:app', 'uds': None, 'fd': None, 'reload': False, 'rel...
Apr 08 17:29:17 raspberrypi python[742]:            │   │      │    │           └ <click.core.Context object at 0x7fa0e39040>
Apr 08 17:29:17 raspberrypi python[742]:            │   │      │    └ <function main at 0x7fa02a4f70>
Apr 08 17:29:17 raspberrypi python[742]:            │   │      └ <Command main>
Apr 08 17:29:17 raspberrypi python[742]:            │   └ <function Context.invoke at 0x7fa0540af0>
Apr 08 17:29:17 raspberrypi python[742]:            └ <click.core.Context object at 0x7fa0e39040>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
Apr 08 17:29:17 raspberrypi python[742]:     return __callback(*args, **kwargs)
Apr 08 17:29:17 raspberrypi python[742]:                        │       └ {'port': 11111, 'host': '0.0.0.0', 'root_path': '/api', 'app': 'app.main:app', 'uds': None, 'fd': None, 'reload': False, 'rel...
Apr 08 17:29:17 raspberrypi python[742]:                        └ ()
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 404, in main
Apr 08 17:29:17 raspberrypi python[742]:     run(
Apr 08 17:29:17 raspberrypi python[742]:     └ <function run at 0x7fa029adc0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
Apr 08 17:29:17 raspberrypi python[742]:     server.run()
Apr 08 17:29:17 raspberrypi python[742]:     │      └ <function Server.run at 0x7fa03c58b0>
Apr 08 17:29:17 raspberrypi python[742]:     └ <uvicorn.server.Server object at 0x7fa0dab4f0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
Apr 08 17:29:17 raspberrypi python[742]:     return asyncio.run(self.serve(sockets=sockets))
Apr 08 17:29:17 raspberrypi python[742]:            │       │   │    │             └ None
Apr 08 17:29:17 raspberrypi python[742]:            │       │   │    └ <function Server.serve at 0x7fa03c5940>
Apr 08 17:29:17 raspberrypi python[742]:            │       │   └ <uvicorn.server.Server object at 0x7fa0dab4f0>
Apr 08 17:29:17 raspberrypi python[742]:            │       └ <function run at 0x7fa0d36c10>
Apr 08 17:29:17 raspberrypi python[742]:            └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Apr 08 17:29:17 raspberrypi python[742]:     return loop.run_until_complete(main)
Apr 08 17:29:17 raspberrypi python[742]:            │    │                  └ <coroutine object Server.serve at 0x7fa0dd74c0>
Apr 08 17:29:17 raspberrypi python[742]:            │    └ <function BaseEventLoop.run_until_complete at 0x7fa070a310>
Apr 08 17:29:17 raspberrypi python[742]:            └ <_UnixSelectorEventLoop running=True closed=False debug=False>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
Apr 08 17:29:17 raspberrypi python[742]:     self.run_forever()
Apr 08 17:29:17 raspberrypi python[742]:     │    └ <function BaseEventLoop.run_forever at 0x7fa070a280>
Apr 08 17:29:17 raspberrypi python[742]:     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
Apr 08 17:29:17 raspberrypi python[742]:     self._run_once()
Apr 08 17:29:17 raspberrypi python[742]:     │    └ <function BaseEventLoop._run_once at 0x7fa070cdc0>
Apr 08 17:29:17 raspberrypi python[742]:     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
Apr 08 17:29:17 raspberrypi python[742]:     handle._run()
Apr 08 17:29:17 raspberrypi python[742]:     │      └ <function Handle._run at 0x7fa07cba60>
Apr 08 17:29:17 raspberrypi python[742]:     └ <Handle <TaskWakeupMethWrapper object at 0x7f9d2c03d0>(<_GatheringFu..., None, None]>)>
Apr 08 17:29:17 raspberrypi python[742]:   File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
Apr 08 17:29:17 raspberrypi python[742]:     self._context.run(self._callback, *self._args)
Apr 08 17:29:17 raspberrypi python[742]:     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
Apr 08 17:29:17 raspberrypi python[742]:     │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f9d2c03d0>(<_GatheringFu..., None, None]>)>
Apr 08 17:29:17 raspberrypi python[742]:     │    │            │    └ <member '_callback' of 'Handle' objects>
Apr 08 17:29:17 raspberrypi python[742]:     │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f9d2c03d0>(<_GatheringFu..., None, None]>)>
Apr 08 17:29:17 raspberrypi python[742]:     │    └ <member '_context' of 'Handle' objects>
Apr 08 17:29:17 raspberrypi python[742]:     └ <Handle <TaskWakeupMethWrapper object at 0x7f9d2c03d0>(<_GatheringFu..., None, None]>)>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
Apr 08 17:29:17 raspberrypi python[742]:     result = await app(  # type: ignore[func-returns-value]
Apr 08 17:29:17 raspberrypi python[742]:                    └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa02a20a0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     return await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:                  │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:                  │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:                  │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:                  │    └ <fastapi.applications.FastAPI object at 0x7f9dccdd60>
Apr 08 17:29:17 raspberrypi python[742]:                  └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa02a20a0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/applications.py", line 273, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await super().__call__(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:                            │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:                            │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:                            └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.middleware_stack(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f9dc57970>
Apr 08 17:29:17 raspberrypi python[742]:           └ <fastapi.applications.FastAPI object at 0x7f9dccdd60>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, _send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f9d3139d0>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <starlette.middleware.cors.CORSMiddleware object at 0x7f9dc57910>
Apr 08 17:29:17 raspberrypi python[742]:           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f9dc57970>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f9d3139d0>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f9dc578b0>
Apr 08 17:29:17 raspberrypi python[742]:           └ <starlette.middleware.cors.CORSMiddleware object at 0x7f9dc57910>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, sender)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f9dc57850>
Apr 08 17:29:17 raspberrypi python[742]:           └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f9dc578b0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <fastapi.routing.APIRouter object at 0x7f9dccddc0>
Apr 08 17:29:17 raspberrypi python[742]:           └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f9dc57850>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await route.handle(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:           │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │     └ <function Mount.handle at 0x7f9fdde790>
Apr 08 17:29:17 raspberrypi python[742]:           └ Mount(path='/v1', name='', app=<fastapi.applications.FastAPI object at 0x7f9dc52190>)
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/routing.py", line 443, in handle
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <fastapi.applications.FastAPI object at 0x7f9dc52190>
Apr 08 17:29:17 raspberrypi python[742]:           └ Mount(path='/v1', name='', app=<fastapi.applications.FastAPI object at 0x7f9dc52190>)
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/applications.py", line 273, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await super().__call__(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:                            │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:                            │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:                            └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.middleware_stack(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313c10>
Apr 08 17:29:17 raspberrypi python[742]:           │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f9d322190>
Apr 08 17:29:17 raspberrypi python[742]:           └ <fastapi.applications.FastAPI object at 0x7f9dc52190>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, _send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f9d313b80>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f9d322310>
Apr 08 17:29:17 raspberrypi python[742]:           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f9d322190>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, sender)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313ca0>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f9d3223d0>
Apr 08 17:29:17 raspberrypi python[742]:           └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f9d322310>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313ca0>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <fastapi.routing.APIRouter object at 0x7f9dc52220>
Apr 08 17:29:17 raspberrypi python[742]:           └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f9d3223d0>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
Apr 08 17:29:17 raspberrypi python[742]:     await route.handle(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313ca0>
Apr 08 17:29:17 raspberrypi python[742]:           │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │     └ <function Route.handle at 0x7f9fdde040>
Apr 08 17:29:17 raspberrypi python[742]:           └ APIRoute(path='/lightning/list-all-tx', name='lightning.list-all-tx', methods=['GET'])
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
Apr 08 17:29:17 raspberrypi python[742]:     await self.app(scope, receive, send)
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f9d313ca0>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f9d322df0>>
Apr 08 17:29:17 raspberrypi python[742]:           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('127.0.0.1', 11111), 'c...
Apr 08 17:29:17 raspberrypi python[742]:           │    └ <function request_response.<locals>.app at 0x7f9dd25790>
Apr 08 17:29:17 raspberrypi python[742]:           └ APIRoute(path='/lightning/list-all-tx', name='lightning.list-all-tx', methods=['GET'])
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
Apr 08 17:29:17 raspberrypi python[742]:     response = await func(request)
Apr 08 17:29:17 raspberrypi python[742]:                      │    └ <starlette.requests.Request object at 0x7f9d31ba60>
Apr 08 17:29:17 raspberrypi python[742]:                      └ <function get_request_handler.<locals>.app at 0x7f9dd1bf70>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
Apr 08 17:29:17 raspberrypi python[742]:     raw_response = await run_endpoint_function(
Apr 08 17:29:17 raspberrypi python[742]:                          └ <function run_endpoint_function at 0x7f9fdc3a60>
Apr 08 17:29:17 raspberrypi python[742]:   File "/home/blitzapi/blitz_api/venv/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
Apr 08 17:29:17 raspberrypi python[742]:     return await dependant.call(**values)
Apr 08 17:29:17 raspberrypi python[742]:                  │         │      └ {'successful_only': False, 'index_offset': 0, 'max_tx': 0, 'reversed': True}
Apr 08 17:29:17 raspberrypi python[742]:                  │         └ <function list_all_tx_path at 0x7f9dea59d0>
Apr 08 17:29:17 raspberrypi python[742]:                  └ <fastapi.dependencies.models.Dependant object at 0x7f9dd24040>
Apr 08 17:29:17 raspberrypi python[742]:   File "./app/lightning/router.py", line 156, in list_all_tx_path
Apr 08 17:29:17 raspberrypi python[742]:     return await list_all_tx(successful_only, index_offset, max_tx, reversed)
Apr 08 17:29:17 raspberrypi python[742]:                  │           │                │             │       └ True
Apr 08 17:29:17 raspberrypi python[742]:                  │           │                │             └ 0
Apr 08 17:29:17 raspberrypi python[742]:                  │           │                └ 0
Apr 08 17:29:17 raspberrypi python[742]:                  │           └ False
Apr 08 17:29:17 raspberrypi python[742]:                  └ <function list_all_tx at 0x7f9dfb1af0>
Apr 08 17:29:17 raspberrypi python[742]: > File "./app/lightning/service.py", line 84, in list_all_tx
Apr 08 17:29:17 raspberrypi python[742]:     return await ln.list_all_tx(successful_only, index_offset, max_tx, reversed)
Apr 08 17:29:17 raspberrypi python[742]:                  │  │           │                │             │       └ True
Apr 08 17:29:17 raspberrypi python[742]:                  │  │           │                │             └ 0
Apr 08 17:29:17 raspberrypi python[742]:                  │  │           │                └ 0
Apr 08 17:29:17 raspberrypi python[742]:                  │  │           └ False
Apr 08 17:29:17 raspberrypi python[742]:                  │  └ <function LnNodeCLNjRPC.list_all_tx at 0x7f9dfa5a60>
Apr 08 17:29:17 raspberrypi python[742]:                  └ <app.lightning.impl.cln_jrpc.LnNodeCLNjRPC object at 0x7f9eb69100>
Apr 08 17:29:17 raspberrypi python[742]:   File "./app/lightning/impl/cln_jrpc.py", line 200, in list_all_tx
Apr 08 17:29:17 raspberrypi python[742]:     for invoice in res[0]:
Apr 08 17:29:17 raspberrypi python[742]:                    └ [None, None, None, None]
Apr 08 17:29:17 raspberrypi python[742]: TypeError: 'NoneType' object is not iterable
Apr 08 17:29:17 raspberrypi python[742]:
Apr 08 17:29:17 raspberrypi python[742]: 2023-04-08 17:29:17 | ℹ️ | logging.py:87 | 127.0.0.1:48778 - "GET /lightning/list-all-tx?reversed=true HTTP/1.0" 500
```
