### ISSUE TITLE
Cannot login to webinterface - Proxmox install

### ISSUE THREAD

**Issue by overcuriousity** [raspiblitz/raspiblitz#4428]
**Describe the bug**
I am unable to login to the webinterface through the IP of my instance. The login page appears, but after entering the password it says "An error occurred: Not Found". 
I am running my instance inside a Proxmox VM. Everything else seems to work, but there might be an issue with the Raspiblitz API i couldn´t narrow down further. It seems to have trouble to retreive some hardware information, which should be handled gracefully i.m.o.

**To Reproduce**
- Provision Raspiblitz dev Branch on Debian 12 VM in Proxmox
- Install Webinterface
- Try to login
- Fail

**Debug file**
Debug Output (From SSH):
```
Generating debug logs. Be patient, this should take maximum 2 minutes ..
sudo: vcgencmd: Befehl nicht gefunden
Redacting ..
# redacting file: /var/cache/raspiblitz/debug.log

***************************************************************
* RASPIBLITZ DEBUG LOGS
***************************************************************
blitzversion: 1.11.0rc2
chainnetwork: bitcoin / main
 15:22:10 up 13 min,  1 user,  load average: 4,66, 4,30, 2,70

*** FAILED SERVICES ***
list any servcies with problems: sudo systemctl list-units --failed
  UNIT LOAD ACTIVE SUB DESCRIPTION
0 loaded units listed.

*** SETUPPHASE / BOOTSTRAP ***
see logs: cat /home/admin/raspiblitz.log
setupPhase--> done
state--> ready

*** BACKGROUNDSERVICE ***
to monitor Background service call: sudo journalctl -f -u background

*** BLOCKCHAIN (MAINNET) SYSTEMD STATUS ***
● bitcoind.service - Bitcoin daemon on mainnet
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-02-20 15:09:31 CET; 12min ago
   Main PID: 6166 (bitcoind)
      Tasks: 24 (limit: 19144)
     Memory: 12.6G
        CPU: 7min 19.157s
     CGroup: /system.slice/bitcoind.service
             └─6166 /usr/local/bin/bitcoind -daemonwait -conf=/mnt/hdd/bitcoin/bitcoin.conf -datadir=/mnt/hdd/bitcoin

Feb 20 15:* BTCNode systemd[1]: Starting bitcoind.service - Bitcoin daemon on mainnet...
Feb 20 15:* BTCNode systemd[1]: Started bitcoind.service - Bitcoin daemon on mainnet.

*** LAST BLOCKCHAIN (MAINNET) ERROR LOGS ***
sudo journalctl -u bitcoind -b --no-pager -n20
Feb 20 15:* BTCNode systemd[1]: Starting bitcoind.service - Bitcoin daemon on mainnet...
Feb 20 15:* BTCNode systemd[1]: Started bitcoind.service - Bitcoin daemon on mainnet.

*** LAST BLOCKCHAIN (MAINNET) INFO LOGS ***
sudo tail -n 50 /mnt/hdd/bitcoin/debug.log
2024-02-20T14:09:31Z txindex thread start
2024-02-20T14:09:31Z Syncing txindex with block chain from height 253664
2024-02-20T14:09:31Z Leaving InitialBlockDownload (latching to false)
2024-02-20T14:09:40Z New block-relay-only v1 peer connected: version: 70016, blocks=831267, peer=1
2024-02-20T14:09:44Z New block-relay-only v1 peer connected: version: 70016, blocks=831267, peer=2
2024-02-20T14:09:46Z Saw new header hash=0000000000000000000323a3b7304ddba3e9f1a6bd762416d1a302096d1ca346 height=831267
2024-02-20T14:09:48Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=3
2024-02-20T14:09:55Z [i2p] Persistent SAM session 5e88e709d3 created, my address=jygaosber6ef66gxuwpjohqocgcntfemyco2ouerl6ss5xuhupca.b32.i2p:0
2024-02-20T14:09:55Z AddLocal(jygaosber6ef66gxuwpjohqocgcntfemyco2ouerl6ss5xuhupca.b32.i2p:0,4)
2024-02-20T14:10:09Z UpdateTip: new best=0000000000000000000323a3b7304ddba3e9f1a6bd762416d1a302096d1ca346 height=831267 version=0x3e000004 log2_work=94.744255 tx=967573606 date='2024-02-20T14:05:58Z' progress=0.999999 cache=2.8MiB(21222txo)
2024-02-20T14:10:10Z Syncing txindex with block chain from height 253722
2024-02-20T14:10:11Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=4
2024-02-20T14:10:12Z New manual v1 peer connected: version: 70016, blocks=831267, peer=7
2024-02-20T14:10:12Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=8
2024-02-20T14:10:13Z Imported mempool transactions from disk: 2320 succeeded, 262 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
2024-02-20T14:10:13Z initload thread exit
2024-02-20T14:10:16Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=9
2024-02-20T14:10:19Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=6
2024-02-20T14:10:35Z [i2p] Error connecting to 4fcc23wt3hyjk3csfzcdyjz5pcwg5dzhdqgma6bch2qyiakcbboa.b32.i2p:0: Unexpected reply to "NAMING LOOKUP NAME=4fcc23wt3hyjk3csfzcdyjz5pcwg5dzhdqgma6bch2qyiakcbboa.b32.i2p": "NAMING REPLY RESULT=INVALID_KEY NAME=4fcc23wt3hyjk3csfzcdyjz5pcwg5dzhdqgma6bch2qyiakcbboa.b32.i2p"
2024-02-20T14:10:40Z Socks5() connect to ***.onion:8333 failed: host unreachable
2024-02-20T14:10:40Z Syncing txindex with block chain from height 257914
2024-02-20T14:10:47Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=10
2024-02-20T14:10:51Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=11
2024-02-20T14:10:59Z New outbound-full-relay v1 peer connected: version: 70016, blocks=831267, peer=12
2024-02-20T14:11:10Z Syncing txindex with block chain from height 261783
2024-02-20T14:11:40Z Syncing txindex with block chain from height 265385
2024-02-20T14:12:10Z Syncing txindex with block chain from height 268805
2024-02-20T14:12:40Z Syncing txindex with block chain from height 271608
2024-02-20T14:13:03Z Saw new header hash=000000000000000000022d060c2f8364c4c7655e30362306018ebd0309ddd409 height=831268
2024-02-20T14:13:18Z UpdateTip: new best=000000000000000000022d060c2f8364c4c7655e30362306018ebd0309ddd409 height=831268 version=0x2b6b2000 log2_work=94.744270 tx=967576746 date='2024-02-20T14:12:57Z' progress=1.000000 cache=4.9MiB(38994txo)
2024-02-20T14:13:18Z Syncing txindex with block chain from height 274022
2024-02-20T14:13:48Z Syncing txindex with block chain from height 276800
2024-02-20T14:14:18Z Syncing txindex with block chain from height 279364
2024-02-20T14:14:48Z Syncing txindex with block chain from height 282582
2024-02-20T14:15:18Z Syncing txindex with block chain from height 285498
2024-02-20T14:15:52Z Syncing txindex with block chain from height 287719
2024-02-20T14:16:14Z New block-relay-only v1 peer connected: version: 70016, blocks=831268, peer=16
2024-02-20T14:16:22Z Syncing txindex with block chain from height 290053
2024-02-20T14:16:56Z Syncing txindex with block chain from height 292087
2024-02-20T14:17:26Z Syncing txindex with block chain from height 294144
2024-02-20T14:17:56Z Syncing txindex with block chain from height 297038
2024-02-20T14:18:27Z Syncing txindex with block chain from height 299146
2024-02-20T14:18:58Z Syncing txindex with block chain from height 301412
2024-02-20T14:19:28Z Syncing txindex with block chain from height 303446
2024-02-20T14:19:52Z New block-relay-only v1 peer connected: version: 70016, blocks=831268, peer=19
2024-02-20T14:20:00Z Syncing txindex with block chain from height 306437
2024-02-20T14:20:30Z Syncing txindex with block chain from height 308532
2024-02-20T14:21:00Z Syncing txindex with block chain from height 310398
2024-02-20T14:21:30Z Syncing txindex with block chain from height 314651
2024-02-20T14:22:01Z Syncing txindex with block chain from height 315334

*** LND (MAINNET) SYSTEMD STATUS ***
● lnd.service - Lightning Network Daemon
     Loaded: loaded (/etc/systemd/system/lnd.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-02-20 15:10:04 CET; 12min ago
   Main PID: 12838 (lnd)
     Status: "Wallet unlocked"
      Tasks: 15 (limit: 19144)
     Memory: 289.0M
        CPU: 4min 29.330s
     CGroup: /system.slice/lnd.service
             └─12838 /usr/local/bin/lnd --configfile=/home/bitcoin/.lnd/lnd.conf

Feb 20 15:* BTCNode systemd[1]: Starting lnd.service - Lightning Network Daemon...
Feb 20 15:* BTCNode systemd[1]: Started lnd.service - Lightning Network Daemon.

*** LAST LND (MAINNET) ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
Feb 20 15:* BTCNode systemd[1]: Starting lnd.service - Lightning Network Daemon...
Feb 20 15:* BTCNode systemd[1]: Started lnd.service - Lightning Network Daemon.

*** LAST LND (MAINNET) INFO LOGS ***
sudo tail -n 50 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2024-02-20 15:10:25.541 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): buffering chan range reply of size=8000
2024-02-20 15:10:25.597 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): buffering chan range reply of size=6454
2024-02-20 15:10:25.597 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): filtering through 46450 chans
2024-02-20 15:10:25.645 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): starting query for 37474 new chans
2024-02-20 15:10:25.646 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:10:25.913 [INF] SRVR: Established connection to: 02a71032ddb75da53d0b447225c3bed8ee2e2b39da622e11a89d58fe5b5b003c8c@*.*.*.*:4011
2024-02-20 15:10:25.913 [INF] SRVR: Finalizing connection to 02a71032ddb75da53d0b447225c3bed8ee2e2b39da622e11a89d58fe5b5b003c8c@*.*.*.*:4011, inbound=false
2024-02-20 15:10:26.079 [INF] NTFN: New block epoch subscription
2024-02-20 15:10:26.079 [INF] PEER: Peer(02a71032ddb75da53d0b447225c3bed8ee2e2b39da622e11a89d58fe5b5b003c8c): Negotiated chan series queries
2024-02-20 15:10:26.079 [INF] DISC: Creating new GossipSyncer for peer=02a71032ddb75da53d0b447225c3bed8ee2e2b39da622e11a89d58fe5b5b003c8c
2024-02-20 15:10:27.714 [INF] SRVR: Established connection to: 022d509049e143b1c5fc5383210acb97a3e5a4b0e0d31dd4c920eee92a4aacd312@*.*.*.*:9735
2024-02-20 15:10:27.714 [INF] SRVR: Finalizing connection to 022d509049e143b1c5fc5383210acb97a3e5a4b0e0d31dd4c920eee92a4aacd312@*.*.*.*:9735, inbound=false
2024-02-20 15:10:27.837 [INF] PEER: Peer(022d509049e143b1c5fc5383210acb97a3e5a4b0e0d31dd4c920eee92a4aacd312): Negotiated chan series queries
2024-02-20 15:10:27.837 [INF] DISC: Creating new GossipSyncer for peer=022d509049e143b1c5fc5383210acb97a3e5a4b0e0d31dd4c920eee92a4aacd312
2024-02-20 15:10:27.837 [INF] NTFN: New block epoch subscription
2024-02-20 15:10:29.005 [ERR] SRVR: Unable to connect to 02f1962328552371769881a9f49c192c0df261f3e0bdf4cd68a4f6d449cc6fd4ad@***.onion:9735: dial proxy failed: socks connect tcp *.*.*.*:9050->###.onion:9735: unknown error host unreachable
2024-02-20 15:10:32.978 [INF] SRVR: Established connection to: 02ed588d777b8512f850eeb0b167e26fd2da2052fb3ccf7a3c3abae2c920acac80@***.onion:9735
2024-02-20 15:10:32.978 [INF] SRVR: Finalizing connection to 02ed588d777b8512f850eeb0b167e26fd2da2052fb3ccf7a3c3abae2c920acac80@***.onion:9735, inbound=false
2024-02-20 15:10:33.825 [INF] PEER: Peer(02ed588d777b8512f850eeb0b167e26fd2da2052fb3ccf7a3c3abae2c920acac80): Negotiated chan series queries
2024-02-20 15:10:33.825 [INF] NTFN: New block epoch subscription
2024-02-20 15:10:33.825 [INF] DISC: Creating new GossipSyncer for peer=02ed588d777b8512f850eeb0b167e26fd2da2052fb3ccf7a3c3abae2c920acac80
2024-02-20 15:10:59.415 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:11:07.102 [INF] INVC: New invoice subscription client: id=1
2024-02-20 15:11:27.929 [INF] CRTR: Processed channels=659 updates=901 nodes=408 in last 1m11.521279738s
2024-02-20 15:11:47.071 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:12:28.056 [INF] CRTR: Processed channels=657 updates=1291 nodes=294 in last 1m0.126974203s
2024-02-20 15:12:31.857 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:13:20.153 [INF] CRTR: Pruning channel graph using block 000000000000000000022d060c2f8364c4c7655e30362306018ebd0309ddd409 (height=831268)
2024-02-20 15:13:20.186 [INF] CRTR: Block 000000000000000000022d060c2f8364c4c7655e30362306018ebd0309ddd409 (height=831268) closed 0 channels
2024-02-20 15:13:22.746 [INF] NTFN: New block: height=831268, sha=000000000000000000022d060c2f8364c4c7655e30362306018ebd0309ddd409
2024-02-20 15:13:22.746 [INF] UTXN: Attempting to graduate height=831268: num_kids=0, num_babies=0
2024-02-20 15:13:27.008 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:13:28.101 [INF] CRTR: Processed channels=543 updates=1074 nodes=177 in last 1m0.045120712s
2024-02-20 15:14:24.992 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:14:28.068 [INF] CRTR: Processed channels=517 updates=1037 nodes=215 in last 59.967006624s
2024-02-20 15:15:11.093 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:15:28.377 [INF] CRTR: Processed channels=620 updates=1248 nodes=167 in last 1m0.308918441s
2024-02-20 15:16:11.515 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:16:28.322 [INF] CRTR: Processed channels=573 updates=1124 nodes=176 in last 59.944316612s
2024-02-20 15:17:14.693 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:17:28.826 [INF] CRTR: Processed channels=463 updates=935 nodes=138 in last 1m0.503695928s
2024-02-20 15:17:56.210 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:18:27.859 [INF] CRTR: Processed channels=597 updates=1189 nodes=179 in last 59.032978677s
2024-02-20 15:18:53.376 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:19:27.666 [INF] CRTR: Processed channels=482 updates=982 nodes=157 in last 59.806839374s
2024-02-20 15:19:42.071 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:20:30.591 [INF] CRTR: Processed channels=565 updates=1126 nodes=159 in last 1m2.924451029s
2024-02-20 15:20:47.395 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels
2024-02-20 15:21:27.717 [INF] CRTR: Processed channels=658 updates=1288 nodes=173 in last 57.126306969s
2024-02-20 15:21:28.249 [INF] DISC: GossipSyncer(025720200b407c1d5ac47a7f0252cbc3e4beb19d3c4c76186ddfb97620cfec1083): querying for 500 new channels

*** CORE LIGHTNING (MAINNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (TESTNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (TESTNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (TESTNET) SYSTEMD STATUS ***
- not activated -

*** BLOCKCHAIN (SIGNET) SYSTEMD STATUS ***
- OFF by config -
*** LND (SIGNET) SYSTEMD STATUS ***
- OFF by config -

*** CORE LIGHTNING (SIGNET) SYSTEMD STATUS ***
- not activated -

*** NGINX SYSTEMD STATUS ***
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─raspiblitz.conf
     Active: active (running) since Tue 2024-02-20 15:08:46 CET; 13min ago
       Docs: man:nginx(8)
   Main PID: 1002 (nginx)
      Tasks: 9 (limit: 19144)
     Memory: 13.8M
        CPU: 79ms
     CGroup: /system.slice/nginx.service
             ├─1002 "nginx: master process /usr/sbin/nginx -g daemon on; master_process on;"
             ├─1003 "nginx: worker process"
             ├─1004 "nginx: worker process"
             ├─1005 "nginx: worker process"
             ├─1006 "nginx: worker process"
             ├─1007 "nginx: worker process"
             ├─1008 "nginx: worker process"
             ├─1010 "nginx: worker process"
             └─1011 "nginx: worker process"

Feb 20 15:* BTCNode systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
Feb 20 15:* BTCNode systemd[1]: Started nginx.service - A high performance web server and a reverse proxy server.

*** LAST NGINX LOGS ***
sudo journalctl -u nginx -b --no-pager -n20
Feb 20 15:* BTCNode systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
Feb 20 15:* BTCNode systemd[1]: Started nginx.service - A high performance web server and a reverse proxy server.
--> CHECK CONFIG: sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

*** BLITZAPI STATUS ***
installed=1
repo='https://github.com/fusion44/blitz_api.git'
branch='dev'
commit='18c66f44f49946638bf2c4317c0df599e0213018'
● blitzapi.service - BlitzBackendAPI
     Loaded: loaded (/etc/systemd/system/blitzapi.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-02-20 15:11:04 CET; 11min ago
    Process: 26374 ExecStartPre=/home/admin/config.scripts/blitz.web.api.sh update-config (code=exited, status=0/SUCCESS)
   Main PID: 26433 (python)
      Tasks: 18 (limit: 19144)
     Memory: 59.3M
        CPU: 3.559s
     CGroup: /system.slice/blitzapi.service
             └─26433 /home/blitzapi/blitz_api/venv/bin/python -m uvicorn app.main:app --port 11111 --host=*.*.*.* --root-path /api

Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:58 | ℹ️ | logging.py:87 | *.*.*.*:45222 - "POST /v1/system/login HTTP/1.0" 404
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:12:03 | ℹ️ | logging.py:87 | *.*.*.*:36136 - "POST /v1/system/login HTTP/1.0" 404

*** LAST BLITZAPI LOGS ***
sudo journalctl -u blitzapi -b --no-pager -n20
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:04 | ℹ️ | logging.py:87 | Uvicorn running on http://*.*.*.*:11111 (Press CTRL+C to quit)
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:04 | ⚠️ | utils.py:69 | Key 'system_ram_mb' not found in Redis DB.
Feb 20 15:* BTCNode python[26433]: Task exception was never retrieved
Feb 20 15:* BTCNode python[26433]: future: <Task finished name='Task-8' coro=<_handle_gather_hardware_info() done, defined at /home/blitzapi/blitz_api/app/system/service.py:99> exception=ValueError("invalid literal for int() with base 10: ''")>
Feb 20 15:* BTCNode python[26433]: Traceback (most recent call last):
Feb 20 15:* BTCNode python[26433]:   File "/home/blitzapi/blitz_api/app/system/service.py", line 102, in _handle_gather_hardware_info
Feb 20 15:* BTCNode python[26433]:     info = await get_hardware_info()
Feb 20 15:* BTCNode python[26433]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 15:* BTCNode python[26433]:   File "/home/blitzapi/blitz_api/app/system/service.py", line 51, in get_hardware_info
Feb 20 15:* BTCNode python[26433]:     return await system.get_hardware_info()
Feb 20 15:* BTCNode python[26433]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 15:* BTCNode python[26433]:   File "/home/blitzapi/blitz_api/app/system/impl/raspiblitz.py", line 308, in get_hardware_info
Feb 20 15:* BTCNode python[26433]:     info["vram_total_bytes"] = int(await redis_get("system_ram_mb")) * 1000 * 1000
Feb 20 15:* BTCNode python[26433]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 20 15:* BTCNode python[26433]: ValueError: invalid literal for int() with base 10: ''
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:04 | ✔️ | service.py:39 | Bitcoin repository initialized
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:07 | ✔️ | lnd_grpc.py:285 | Initialization complete.
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:55 | ℹ️ | logging.py:87 | *.*.*.*:45220 - "GET /v1/setup/status HTTP/1.0" 404
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:11:58 | ℹ️ | logging.py:87 | *.*.*.*:45222 - "POST /v1/system/login HTTP/1.0" 404
Feb 20 15:* BTCNode python[26433]: 2024-02-20 15:12:03 | ℹ️ | logging.py:87 | *.*.*.*:36136 - "POST /v1/system/login HTTP/1.0" 404

*** BLITZ WebUI STATUS ***
installed=1
repo='https://github.com/raspiblitz/raspiblitz-web.git'
branch='master'
commit='3d3d569a4d4b478b06bfae095589e2b6d7fcaf85'

- TOUCHSCREEN is OFF by config
- Loop is OFF by config

*** LND-RTL ***
● RTL.service - RTL Webinterface
     Loaded: loaded (/etc/systemd/system/RTL.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-02-20 15:10:04 CET; 12min ago
   Main PID: 17125 (node)
      Tasks: 11 (limit: 19144)
     Memory: 35.8M
        CPU: 1.059s
     CGroup: /system.slice/RTL.service
             └─17125 /usr/bin/node /home/rtl/RTL/rtl

- CL-RTL is OFF by config

*** LAST 20 ElectRS LOGS ***
sudo journalctl -u electrs -b --no-pager -n20
Feb 20 15:* BTCNode systemd[1]: Started electrs.service - Electrs.
Feb 20 15:* BTCNode electrs[12594]: Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/mnt/hdd/app-storage/electrs/db/bitcoin", db_log_dir: None, daemon_dir: "/home/electrs/.bitcoin", daemon_auth: UserPass("raspibolt", "<sensitive>"), daemon_rpc_addr: *.*.*.*:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs v0.10.2 - the Electrum Rust Server on your RaspiBlitz", signet_magic: f9beb4d9, args: [] }

*** ElectRS Status ***
##### STATUS ELECTRS SERVICE
version='v0.10.2'
configured=1
serviceInstalled=2
serviceRunning=1
localIP='*.*.*.*'
publicIP='*.*.*.*'
portTCP='50001'
localTCPPortActive=1
publicTCPPortAnswering=0
portSSL='50002'
localHTTPPortActive=1
publicHTTPPortAnswering=0
TorRunning=1
nginxTest=1
serviceRunning=1
electrumResponding=0
initialSynced=0
infoSync='Building Index (please wait)'

- LIT is OFF by config
- LNDg is OFF by config
* BTCPayServer is OFF by config
* BTC-RPC-Explorer is OFF by config
- LNbits is OFF by config
- Thunderhub is OFF by config
- SPECTER is OFF by config
- SPHINX is OFF by config
- FINTS is OFF by config

*** MOUNTED DRIVES ***
df -T -h
Dateisystem    Typ      Größe Benutzt Verf. Verw% Eingehängt auf
udev           devtmpfs  7,8G       0  7,8G    0% /dev
tmpfs          tmpfs     1,6G    928K  1,6G    1% /run
/dev/sda1      ext4       31G     11G   19G   35% /
tmpfs          tmpfs     7,9G       0  7,9G    0% /dev/shm
tmpfs          tmpfs     5,0M       0  5,0M    0% /run/lock
tmpfs          tmpfs      32M     24K   32M    1% /var/cache/raspiblitz
/dev/sdb1      ext4      1,2T    608G  513G   55% /mnt/hdd
tmpfs          tmpfs     1,6G       0  1,6G    0% /run/user/1001

*** SD CARD HOMES ***
sudo du -ahd1 /home
449M    /home/admin
578M    /home/blitzapi
976M    /home/circuitbreaker
2,1G    /home/mempool
431M    /home/rtl
684M    /home/electrs
60K     /home/pi
16K     /home/bitcoin
5,1G    /home

*** LOGFILES ***
Archived and active journals take up 32.0M in the file system.
51M     /var/log

*** DATADRIVE ***
# RASPIBLITZ DATA DRIVE Status

# BASICS
isMounted=1
isBTRFS=0
hddRaspiData=1
hddRaspiVersion='1.11.0rc2'
isSMART=0
isSSD=1
datadisk='sdb'
datapartition='sdb1'
hddCandidate='sdb'
hddPartitionCandidate='sdb1'
hddTemperature=
hddBlocksBitcoin=1
hddBytes=1288488091648
hddGigaBytes=1199
hddTBSize='1TB'
hddUsedInfo='1TB 55%'
hddDataFreeBytes=550463889408
hddDataFreeKB=537562392
hddDataFreeGB=512
hddAdapterUSB=''
hddAdapterUSAP=0

# RAID
isRaid=0
raidCandidates=0

# SWAP
isSwapExternal=1
SwapExternalPath='/mnt/hdd/swapfile'

smartctl 7.3 2022-02-28 r5338 [x86_64-linux-6.1.0-18-amd64] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               QEMU
Product:              QEMU HARDDISK
Revision:             2.5+
Compliance:           SPC-3
User Capacity:        *.*.*.*.800 bytes [1,28 TB]
Logical block size:   512 bytes
LU is thin provisioned, LBPRZ=0
Rotation Rate:        Solid State Device
Device type:          disk
Local Time is:        Tue Feb 20 15:22:13 2024 CET
SMART support is:     Unavailable - device lacks SMART capability.

=== START OF READ SMART DATA SECTION ===
Current Drive Temperature:     0 C
Drive Trip Temperature:        0 C

Error Counter logging not supported

Device does not support Self Test logging

*** NETWORK ***
localip=*.*.*.*
localiprange=enp0s18...0/24
dhcp=1
network_device=ens18


*** ZRAM ***
downloaded=1
serviceLoaded=1
serviceActive=1

*** HARDWARE TEST RESULTS ***
UndervoltageReports in Logs: 0

*** SYSTEM CACHE STATUS ***
system_ram_mb=""
system_vm_vagrant="0"
system_count_start_blockchain="6"
system_count_undervoltage="0"
system_up="806"
system_board=""
system_ups_status="OFF"
system_cpu_load=" 4,66, 4,30, 2,70"
system_ram_gb="17"
system_ups_battery=""
system_init_time="1708438127"
system_count_start_lightning="7"
system_ram_available_mb=""
ln_default_wallet_onchain_pending="0"
ln_default_recovery_mode="0"
ln_default_version="0.17.3-beta"
ln_default_wallet_channels_balance=****
ln_default_peers="5"
ln_default_running="1"
ln_default_channels_active="0"
ln_default_ready="1"
ln_default_sync_initial_done="1"
ln_default_alias=****
ln_default_wallet_onchain_balance=****
ln_default_error_full=""
ln_default_wallet_channels_pending="0"
ln_default_tor="1"
ln_default_fees_total="0"
ln_default_error_short=""
ln_default_locked="0"
ln_default_channels_inactive="0"
ln_default_sync_chain="1"
ln_default_channels_pending="0"
ln_default_activated="1"
ln_default_online="1"
ln_default_sync_progress="100.00"
ln_default_recovery_done="0"
ln_default_channels_total="0"
btc_default_blocks_behind="0"
btc_default_error_full=""
btc_default_blocks_headers="831268"
btc_default_ready="1"
btc_default_error_short=""
btc_default_sync_initialblockdownload="0"
btc_default_sync_initial_done="1"
btc_default_mempool_transactions="3629"
btc_default_blocks_verified="831268"
btc_default_activated="1"
btc_default_version="v26.0.0"
btc_default_synced="1"
btc_default_online="1"
btc_default_blocks_data_kb="610679196"
btc_default_port="8333"
btc_default_sync_progress="0.9999971750408632"
btc_default_running="1"
btc_default_sync_percentage="100.00"
btc_default_peers="13"
*** POSSIBLE ERROR REPORTS ***

```

**Comment by rootzoll** [comment]
We made some optimizations for Proxmox and when I tested the WebUI on my Proxmox testinstance it works fine, but I can see still similar errors in my API deug - so i opened an issue on the API repo to address this issue: https://github.com/fusion44/blitz_api/issues/271

**Comment by overcuriousity** [comment]
I moved to a custom archlinux implementation (roughly following raspibolt) in the meantime, which runs good on proxmox.
However, I would be happy to assist with testing and improvements for raspiblitz on proxmox, if my assistance would benefit the project.

**Comment by rootzoll** [comment]
@overcuriousity we stick so far to debian as a base - v1.11.3rc1 is getting closer (two weeks) any feedback & testing on Proxmox welcome.
