### ISSUE TITLE
Update LND & update protobuffs

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4749]
Because lnd v0.17.5 was the latest v0.17.x release - just make the jump tp v0.18.x with RaspiBlitz v1.12.0 & recompile protobuffs
https://github.com/lightningnetwork/lnd/releases

**Comment by rootzoll** [comment]
LND v0.19.0 is out .. adding to v1.12.0
https://github.com/lightningnetwork/lnd/releases/tag/v0.19.0-beta

**Comment by rootzoll** [comment]
Test ./config.scripts/lnd.initwallet.py with new proto buffs .. re adapt by protobuffs README

```
admin@192.168.16.103:~ ₿ ./config.scripts/lnd.initwallet.py
# creating or recovering the LND wallet
# lnd.initwallet.py new [mainnet|testnet|signet] [walletpassword] [?seedpassword]
# lnd.initwallet.py seed [mainnet|testnet|signet] [walletpassword] ["seeds-words-seperated-spaces"] [?seedpassword]
# lnd.initwallet.py unlock [mainnet|testnet|signet] [walletpassword] [recovery_window]
# lnd.initwallet.py scb [mainnet|testnet|signet] [filepathSCB] [macaroonPath]
# lnd.initwallet.py change-password [mainnet|testnet|signet] [walletpassword-old] [walletpassword-new]
err='missing parameters'
admin@192.168.16.103:~ ₿ ./config.scripts/lnd.initwallet.py seed 12345678
Traceback (most recent call last):
  File "/home/admin/./config.scripts/lnd.initwallet.py", line 31, in <module>
    from lndlibs import walletunlocker_pb2 as lnrpc
  File "/home/admin/config.scripts/lndlibs/walletunlocker_pb2.py", line 23, in <module>
    import lightning_pb2 as lightning__pb2
ModuleNotFoundError: No module named 'lightning_pb2'
```
