### ISSUE TITLE
LND service not running | Enters failed state after panic & invalid argument

### ISSUE THREAD

**Issue by RanaMX** [raspiblitz/raspiblitz#665]
Hello,

My lightning runs into the following errors which results in a failed state/ error loop:
panic: invalid freelist page: 0, page type is unknown<00> 
lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
Complete Errorlog: https://termbin.com/h9t1

Before I fried my Raspiblitz HDD in a reboot due to undervoltage (used 1A outlet from Router :S ) but I could still get the .lnd-rescue-xxx.tar file off the HDD later on.
Now I have a new SSD, redownloaded the complete blockchain, but with raspiblitz v1.2 and also with v1.1 and v1.0 my lightning always gets stuck in an error loop.
With v1.0 and v1.1 it hangs in the filtering blockchain "?/5...." stage, with v1.2 it tells me straight away "The LND service is not running."

I have tried to find a solution with other issue# but could not find it. On current v1.2 i have run the following reports, hoping you know what is wrong.
I think worst case my .tar file is corrupted, but since Lightning does not even start I hope it could be another issue.

I currently run on 5V 2.5A for the raspiblitz and apart 5V 1A with Y-cable for the SSD. Hardwaretest says the power supply seems ok, but could be better for stable operations, it also gets hot. I have two 5V 3A chargers coming next week and will install a fan into the housing.

Hope you can help me!!!
Much thanks!

**Initial Start up v1.2:**

> ****************************************
> * The LND service is not running.
> ****************************************
> If you just started some config/setup, this might be OK.
> 
> 8 RESTARTS DETECTED - LND might be in a error loop
> Jun 23 01:57:38 RanaMX lnd[22811]: panic: invalid freelist page: 0, page type is unknown<00>
> 
> ****************************************
> * The LND service is not running.
> ****************************************
> If you just started some config/setup, this might be OK.
> 
> 8 RESTARTS DETECTED - LND might be in a error loop
> Jun 23 01:57:38 RanaMX lnd[22811]: panic: invalid freelist page: 0, page type is unknown<00>
> Jun 23 01:57:38 RanaMX lnd[22811]: goroutine 1 [running]:
> Jun 23 01:57:38 RanaMX lnd[22811]: github.com/coreos/bbolt.(*freelist).read(0x3044340, 0x63cf6000)
> Jun 23 01:57:38 RanaMX lnd[22811]:         /Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/freelist.go:266 +0x23c
> Jun 23 01:57:38 RanaMX lnd[22811]: github.com/coreos/bbolt.(*DB).loadFreelist.func1()
> Jun 23 01:57:38 RanaMX lnd[22811]:         /Users/roasbeef/gocode/pkg/mod/github.com/coreos/bbolt@v1.3.2/db.go:310 +0xf0
> Jun 23 01:57:38 RanaMX lnd[22811]: sync.(*Once).Do(0x2db40c0, 0x3063d28)
> Jun 23 01:57:38 RanaMX lnd[22811]:         /usr/local/go/src/sync/once.go:44 +0xb8
> 
> -> Use following command to debug: /home/admin/XXdebugLogs.sh
> -> To force Main Menu run: /home/admin/00mainMenu.sh
> -> To try restart: sudo shutdown -r now

**admin@RanaMX:~ $ sudo journalctl -f -u lnd**

> -- Logs begin at Sun 2019-06-23 02:03:43 BST. --
> Jun 23 02:17:19 RanaMX systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Jun 23 02:17:19 RanaMX systemd[1]: lnd.service: Unit entered failed state.
> Jun 23 02:17:19 RanaMX systemd[1]: lnd.service: Failed with result 'exit-code'.
> Jun 23 02:18:19 RanaMX systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
> Jun 23 02:18:20 RanaMX systemd[1]: Stopped LND Lightning Daemon.
> Jun 23 02:18:20 RanaMX systemd[1]: Starting LND Lightning Daemon...
> Jun 23 02:18:20 RanaMX systemd[1]: Started LND Lightning Daemon.
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Unit entered failed state.
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Failed with result 'exit-code'.

**admin@RanaMX:~ $ sudo systemctl status lnd**

> ● lnd.service - LND Lightning Daemon
>    Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: exit-code) since Sun 2019-06-23 02:18:20 BST; 46s ago
>   Process: 2607 ExecStart=/usr/local/bin/lnd --externalip=${publicIP}:${lndPort} (code=exited, status=2)
>   Process: 2603 ExecStartPre=/home/admin/config.scripts/blitz.systemd.sh log lightning STARTED (code=exited, status=0
>  Main PID: 2607 (code=exited, status=2)
>    CGroup: /system.slice/lnd.service
> 
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Unit entered failed state.
> Jun 23 02:18:20 RanaMX systemd[1]: lnd.service: Failed with result 'exit-code'.
> lines 1-11/11 (END)

**Comment by rootzoll** [comment]
Not sure exactly why ... can you check your raspiblitz config and post the values of `lndPort` and `publicIP` here? --> terminal: `cat /mnat/hdd/raspiblitz.conf`.

Also if your RaspiBlitz was funded/channels and you were running v1.2 ... please check if you can find and backup the following file: `/home/admin/.lnd/data/chain/bitcoin/mainnet/channel.backup`

**Comment by RanaMX** [comment]
Hi rootzoll,
unfortunately the raspiblitz was still on v1.1 when HDD got damaged....

Now with the new SSD on v1.2 the cat command does not seem to work, the output is:

> admin@RanaMX:~ $ cat /mnat/hdd/raspiblitz.conf
> cat: /mnat/hdd/raspiblitz.conf: No such file or directory

**Comment by rootzoll** [comment]
Sorry there was a typo - it should be: `cat /mnt/hdd/raspiblitz.conf`

**Comment by RanaMX** [comment]
Perfect, here comes the output
IP and port seem correct. lndAddress empty.
Starting it up today I also got the message on the raspiblitz screen "Give root password for maintenance or press Ctr+D to continue"
Connecting a USB keyboard and pressing Ctr+D starts it up normal. It was shutdown always via terminal & sudo shutdown now

> admin@RanaMX:~ $ cat /mnt/hdd/raspiblitz.conf
> # RASPIBLITZ CONFIG FILE
> raspiBlitzVersion='1.2'
> network=bitcoin
> chain=main
> hostname=RanaMX
> **publicIP='189.166.43.184'**
> autoPilot=off
> autoNatDiscovery=off
> runBehindTor=off
> rtlWebinterface=off
> **lndPort='9735'**
> lndAddress=''

**Comment by RanaMX** [comment]
Well, meanwhile I have done the following:
Changed to 3A power supply and better cooling, very rarely now that I have untervoltage warnings in the logs.
Made a complete new installation from scratch as a test and it started up just fine, so Hardware appears to be fine
Got a new recovery gz.tar file from a new 1.2 SD installation from failing HDD
Installed 1.2 again from scratch on SSD with new .gz.tar file and same result =(
https://termbin.com/rr9u

I still have the assumption that maybe the gz.tar file is corrupted since the old HDD is failing, despite the fact that I can download it without failures from old HDD.

Will try another new recovery installation when v1.3 comes out and if it does not work recover with seedphrase and forget about the onchain funds....

**Comment by RanaMX** [comment]
Just tried to access the lightning channels with the Lightning Desktop App, but also unsuccessful. When I exchange the files in the lnd folder of AppData the Lightning Desktop App starts up and stays in the Main screen just saying LIGHTNING By Lightning Labs, INC, not advancing any further.
Also one additional doubt, by now I have pulled 3 different rescue files and all have different names and especially file sizes, is this normal?
![lnd backup](https://user-images.githubusercontent.com/52116212/60770852-3756e380-a0a5-11e9-9138-b575c375772d.JPG)

**Comment by fkochdev** [comment]
I have the same problem. LND service not running, it enters a failed state after panic.

Tried to clean HDD, copy the blockchain from anonther raspiblitz and tried to restore my old LND node with the .gz.tar backup file. Problem remains.

EDIT: Here is what I did: Force-started the main menu, enabled Tor - everything works fine. So it's a port problem I guess?

EDIT 2: Damn. I was just lucky for a short time. Problem remains:
*** LAST LND ERROR LOGS ***
sudo journalctl -u lnd -b --no-pager -n12
-- Logs begin at Wed 2019-07-17 15:40:17 BST, end at Wed 2019-07-17 16:03:06 BST. --
Jul 17 16:00:40 NodeName systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 17 16:00:40 NodeName systemd[1]: lnd.service: Unit entered failed state.
Jul 17 16:00:40 NodeName systemd[1]: lnd.service: Failed with result 'exit-code'.
Jul 17 16:01:40 NodeName systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jul 17 16:01:40 NodeName systemd[1]: Stopped LND Lightning Daemon.
Jul 17 16:01:40 NodeName systemd[1]: Starting LND Lightning Daemon...
Jul 17 16:01:40 NodeName systemd[1]: Started LND Lightning Daemon.
Jul 17 16:02:23 NodeName lnd[27867]: panic: page 13360 already freed
Jul 17 16:02:23 NodeName lnd[27867]: goroutine 1 [running]:
Jul 17 16:02:23 NodeName systemd[1]: lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 17 16:02:23 NodeName systemd[1]: lnd.service: Unit entered failed state.
Jul 17 16:02:23 NodeName systemd[1]: lnd.service: Failed with result 'exit-code'.

*** LAST 30 LND INFO LOGS ***
sudo tail -n 30 /mnt/hdd/lnd/logs/bitcoin/mainnet/lnd.log
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 02b6f2164152f8451efcbeac3e5e3ad1867a450329973fca0e06c8396b9fb210ab from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 02eff1ddfb22334e9cba0f24b41a624e50a0e755023102acf624327a0b7e894c36 from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 0340023797652d7ba0d8065f8fb412fd537dee0875634a68679d0415d5a2369a03 from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 03bfe4008a3dcf2f8f6d892d00e61086abdc23b4bdeae59319e9ad884b2038166d from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 029d91e731b4f03de2db7d83a0b61a3c2c45c1eac67292b87e31583ee6c696b5be from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 02ceb91a6a27520ae8d8f4d933c12e58108fe612bd810607786fcb040c460275e1 from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 0346c84a15d0ac1d724f64cbaf3726fbaa33e6c95d15abd513c1767b9945884fd6 from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 023e18169f9b4253eff56bd7035660b28c95e61e12fabc03f4aef59d102d55bbb0 from channel graph
2019-07-17 16:02:23.899 [INF] CHDB: Pruned unconnected node 02ead83740f6b123e3f468736ed6026e1898305811c93ce566198ffe24fab074fb from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03cbb3b990aeb8d06bd806b3f289840971979c43a64a40f5a26c9ba77a570a9187 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03d1af91da3c0cad7d3501b2031db9bd80628e9e829f5d1fe8985a3116176cbf30 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03df89fb4a29bfcb70dccd899492498c6498e50b85a46901e4492d2263072c530a from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03ed88bb37c8c53c509d9a355e5a103614ebd30c98b7895ea4ccaddee262db190d from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 025a596f3023eb914d6041bbb75d9d274b8131596aa9c6eecff72fa45de9927fbc from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03c2b5e97173e2ff7baea106a34a165e0213b6c5148441ea97785b35a78a506299 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 02d379fd4c3e6ccced10ec93aa87eb0478587152f88fde963f773d2101bcb84ba2 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 02e7c2b4cb7d9ebf11e02bc9a6db4ed9d5b48b5a77f5ab9ffd9102adfca0add902 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 03d2d2f3b8acdb677b380911da3b8920b10f5d531644b8ca54d2695d25417bc9a9 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 023744412f66c0018d08f42fdcf4e364cbe6b0a472e4cc86e8c68d719cfb426975 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 0273209369cf43965cf46be5ba41dd5e04756a658c440c873083f36344dc01a040 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 023095308c495f22794c8628b4b9605701e2f5e410968aaf475118690c109e048a from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 027be9e7e2bc7ec87177ac298c01517ef46f979e1e3acec46efcf7a6f1b3ddadff from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned unconnected node 021da81caec2f0d8cd8471b7d2767b3ee549b21d5f6cb5c74ec7871d6efa233ec1 from channel graph
2019-07-17 16:02:23.900 [INF] CHDB: Pruned 3720 unconnected nodes from the channel graph
2019-07-17 16:02:23.902 [INF] RPCS: Stopping RPC Server
2019-07-17 16:02:23.902 [INF] RPCS: Stopping SignRPC Sub-RPC Server
2019-07-17 16:02:23.902 [INF] RPCS: Stopping ChainRPC Sub-RPC Server
2019-07-17 16:02:23.902 [INF] RPCS: Stopping InvoicesRPC Sub-RPC Server
2019-07-17 16:02:23.903 [INF] RPCS: Stopping WalletKitRPC Sub-RPC Server
2019-07-17 16:02:23.904 [INF] LTND: Shutdown complete

**Comment by fluidvoice** [comment]
I'm running Raspiblitz v1.3 in a x86 VM and got the same LND failure error due to panic/crash and LND cannot restart itself.   
> lnd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

This was after running perfectly then enabled Tor which was not working, then turning Tor off again and resetting LND via the REPAIR RESET-LND menu selection.  Will followup in another issue: https://github.com/openoms/raspiblitz/issues/56#issue-471142452

**Comment by nyxnor** [comment]
@RanaMX Please close this issue.

**Comment by RanaMX** [comment]
Before closing just the hint for anybody reading this in the future: I could never recover the channels with the raspiblitz, I ended up using guggero's chantools to recover sats from some of the LN channels.

**Comment by nyxnor** [comment]
@RanaMX Chantools was later added to v1.7 https://github.com/rootzoll/raspiblitz/pull/1962
